### ISSUE TITLE
Cache the serving URL for files

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#102]
See here: https://github.com/potatolondon/djangae/blob/master/djangae/storage.py#L106

This does an RPC call on every request. We should cache that!

**Comment by owad** [comment]
This commit can be found useful when implementing caching https://github.com/potatolondon/djangae/commit/d77897bf5523ce478d6a5cad417b1635f4991a0b

**Comment by adamalton** [comment]
Kazade says that his plan is now nonsense, but that we should still implement caching of the serving URL.

**Comment by Kazade** [comment]
Already done
