### ISSUE TITLE
Use of deprecated resources in forms/fields.py

### ISSUE THREAD

**Issue by kaustubhkurve** [potatolondon/djangae#1030]
Hi!

There are a few instances of usage of deprecated django methods/attributes in forms/fields.py, which causes the creation of model instances from the admin site to fail if that model has a GenericRelationField defined.
These are the deprecated methods/attributes I could find.
1) models.get_apps in [L210](https://github.com/potatolondon/djangae/blob/master/djangae/forms/fields.py#L210). Removed in Django>=1.9 in favour of apps.get_app_configs(Please see [L390](https://github.com/django/django/blob/stable/1.8.x/django/apps/registry.py#L390))
2) models.get_models in [L211](https://github.com/potatolondon/djangae/blob/master/djangae/forms/fields.py#L211) and [L224](https://github.com/potatolondon/djangae/blob/master/djangae/forms/fields.py#L224). Replaced by apps.get_models in Django>=1.9.
3) m._meta.module_name(Options.module_name) in [L187](https://github.com/potatolondon/djangae/blob/master/djangae/forms/fields.py#L187). Replaced by m._meta.model_name(Options.model_name).

Steps to reproduce
1) Define a model with a GenericRelationField.
2) Creating a new instance of the model from the admin site fails.

* Djangae version: master@6e23d264
* Django version: 1.10
* App Engine SDK version: 1.9.64
* Using Cloud SDK: yes

**Comment by adamalton** [comment]
Thanks for reporting this.  Looks like these should be fairly easy fixes.
