### ISSUE TITLE
ComputedCollationField fails in multiple ways

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#1048]
Issue description

ComputedCollationField will throw an error like this if you are computing the collation from a long string.

```
BadRequestError: The value of property "XXXXXX" is longer than 1500 bytes.
```

This is because the collation string is much longer than the original. A better behaviour here would be to log a warning and truncate the data. As this field is used for ordering it's unlikely that differences beyond the first 1500 bytes will make a huge difference to ordering. It's far better than dying on save.

Steps to reproduce

Traceback or other info

* Djangae version: 0.9.10
* Django version: 1.11
* Using Cloud SDK: no

**Comment by adamalton** [comment]
The other issue is that the value that the collator gives us is a tuple of numbers, but we save it as a string.  So if instance A has `(10000, 1, 1, 1)` and instance B has `(9, 1, 1, 1)` and they're sorted in ascending order then they'll come back in the order A, B.  Which definitely isn't right.  This is also the reason why the string also exceeds the 1500 bytes limit so often.

We could/should possibly do the truncation thing as well, but could allow it via a kwarg, e.g.

```python
name_ordering = ComputedCollationField("name", allow_truncation=True)
```

Talking of which, we should possibly also check that the source field is not a `TextField`?
