### ISSUE TITLE
Write tests for #103

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#105]
#103 added a missing field to gauth, thus proving that we don't have coverage for that. 

We need tests covering the authentication middleware.

**Comment by haikoschol** [comment]
Is this ticket still relevant? The code has changed a bit since, wrt to `is_superuser`. The test `CustomPermissionsUserModelBackendTest` accesses the attribute on an instance of `GaeDatastoreUser`.

**Comment by Kazade** [comment]
Aha! Probably not! Closing thanks!
