### ISSUE TITLE
Backup uses undefined url

### ISSUE THREAD

**Issue by wittfabian** [potatolondon/djangae#1071]
The backup function tries to access the following url, but it gets an http 301 because the url does not exist. I did not find the url under djangae.urls either.

`GET /_ah/datastore_admin/backup.create?name=djangae-backups&gs_bucket_name=<bucket>%2Fdjangae-backups%2F20180616-082310&filesystem=gs&kind=<kind>&queue=backups`

In addition, DJANGAE_BACKUP_QUEUE is ignored and the default queue is used.

* Djangae version: 0.9.11
* Django version: 1.11
* App Engine SDK version: 1.9.64
* Using Cloud SDK: yes

**Comment by adamalton** [comment]
Is it because you need to enable the Datastore Admin? https://cloud.google.com/appengine/docs/standard/python/console/managing-datastore#enabling_datastore_admin

**Comment by wittfabian** [comment]
That is an option. Thanks for the hint.

This note should be included in the documentation:
https://djangae.readthedocs.io/en/latest/backup/

**Comment by wittfabian** [comment]
That's it. thank you!

**Comment by adamalton** [comment]
👍
