### ISSUE TITLE
Deployment instructions

### ISSUE THREAD

**Issue by morninj** [potatolondon/djangae#108]
Would be great to have instructions for deploying the project to GAE.

**Comment by davide-ceretti** [comment]
Once you have registered your app to GAE and update app.yaml deploying should be as simple as ```appcfg.py update .```. Are you looking for any additional information?

**Comment by morninj** [comment]
That's it. I just thought it would be helpful to make it explicit for those who haven't spent much time with GAE. Maybe something like https://github.com/potatolondon/djangae-scaffold/commit/e82f521ff6ddf555994f44fdd7a4899b40a414a4.

**Comment by Kazade** [comment]
Sure, want to make a PR with that commit and I'll merge?

**Comment by morninj** [comment]
Done: https://github.com/potatolondon/djangae/pull/244
