### ISSUE TITLE
Saved values for SetField with choices are not selected in Django admin change form

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#1091]
If you have a `SetField` on a model, and the SetField has choices, and you register that model with the Django admin, by default you'll get a multiple select widget for it.  But if you're editing an existing instance of that object then the saved values (`<option>`s) are not selected in the multiple `<select>` input.

The reason for this is:
1. `djangae.fields.iterable.IterableField.formfield` returns a `django.forms.MultipleChoiceField` as the form field.
2. `django.forms.MultipleChoiceField` uses `django.forms.SelectMultiple` as its widget.
3. The `format_value` method on `django.forms.SelectMultiple` requires the existing value to be a `list` or `tuple` in order to work.   So the fact that it's a `set` means that it doesn't.

So you would think that a simple workaround would be to override the [formfield_overrides](https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_overrides) attribute on your Django `Admin` class.  But that doesn't work because for some unknown reason, the Django admin code ignores the `formfield_overrides` if the field has choices!  What?!  (See [django.contrib.admin.options.BaseModelAdmin.formfield_for_dbfield](https://github.com/django/django/blob/stable/1.11.x/django/contrib/admin/options.py#L135-L138).)

So there are 2 problems here:

1. The fact that we need to somehow override the `format_value` method on the widget.
2. The fact that we can't easily shoehorn a custom widget into place due what I think is a bug in the Django admin (or at least an admission in the documentation).

* Djangae version:  master@e5a86b77140e2ce0fbe464eb2afd18fe3d977a5e
* Django version: 1.11
* App Engine SDK version: n/a
* Using Cloud SDK: n/a

**Comment by Kazade** [comment]
I *think* this is fixed by #1007

**Comment by adamalton** [comment]
Yep, from a read of the code, I think that will have fixed it.

**Comment by adamalton** [comment]
(If the PR had tests then we could say for sure 😀  )
