### ISSUE TITLE
Weird crash with a certain query

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#1097]
Issue description

Earlier I did a query similar to the following (models and fields replaced)

```
class SomeModel(models.Model):
    thing = models.ForeignKey(Thing)
    name = models.CharField(max_length=100)

SomeModel.objects.filter(thing_id=1).exclude(name="Ted")
```

And it exploded in the depths of Djangae multi-query magic with a CPython exception (!)

Steps to reproduce

 - Run the above query, although I can't guarantee there wasn't some other thing that is related

Traceback or other info

* Djangae version: 169599a03cef59f0e0770adeb79438220a6cf44b
* Django version: 1.11
* App Engine SDK version: 1.9.54
* Using Cloud SDK: no

**Comment by adamalton** [comment]
This looks very much like it's a bug in the SDK, rather than anything that we're doing.  My suspicion is that the reason why we see this problem with exclude queries is because they use the Djangae MultiQuery which runs multiple simultaneous queries *in threads*.

**Comment by adamalton** [comment]
I made an issue on the Cloud Datastore issue tracker: https://issuetracker.google.com/issues/113308038

**Comment by adamalton** [comment]
Weirdly, those tests pass on Travis 🤷‍♂️

**Comment by Kazade** [comment]
Yeah I'm suitably convinced this isn't us and is a Datastore stub problem.

**Comment by adamalton** [comment]
I think it's to do with the database _creation_ not being thread-safe.  Which I think would explain it.  (Although wouldn't explain why it works on Travis.)
