### ISSUE TITLE
Google Cloud SDK version check

### ISSUE THREAD

**Issue by seawolf42** [potatolondon/djangae#1100]
If the local version of the Google Cloud SDK is newer than the highest supported version, the user gets cryptic messages (usually related to import errors). Related to #1035, #1042, 

Steps to reproduce:
```bash
$ gcloud components install --version=171.0.0
$ python manage.py runserver
```

Traceback or other info:
(various messages, depending on which SDK version is installed)

* Djangae version: 0.9.11 (also master/HEAD)
* Django version: all
* App Engine SDK version: 1.9.58
* Using Cloud SDK: yes

**Comment by jacobg** [comment]
The commit for this issue seems to cause this regression:
#1103

Please comment.

**Comment by davidwtbuxton** [comment]
The changes in #1101 were reverted in #1104. See comments in #1103 for details of what breaks when this version of Djangae is used on App Engine.

**Comment by jacobg** [comment]
Thanks!

**Comment by seawolf42** [comment]
Sorry guys, this is really embarrassing. I'll get an updated version of this in place ASAP.

**Comment by davidwtbuxton** [comment]
@seawolf42 Not embarrassing, we should have caught it in review before merging. TIL that the update checker code isn't available in production.

**Comment by jacobg** [comment]
Would it be possible for the CI testing to deploy a scaffold app to production and perhaps call a basic test endpoint and verify 200 response? That might help test gaps between local sdk and production sandbox.
