### ISSUE TITLE
Auto-calculate buffer_time for defer_iteration_with_finalize

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#1139]
Issue description

In `djangae.deferred.defer_iteration_with_finalize`, there is a `buffer_time` kwarg which allows you to specify the minimum number of seconds that must be remaining in the task execution time in order for it to process another entity, rather than redeferring itself.

But rather than requiring the user to specify this buffer time, we could just calculate it automatically by setting it to the longest time that any of the entities in the shard have taken to process so far, probably plus some margin, e.g. 10%.  We would do this by just timing each iteration of the processing loop and keeping a variable with the longest time.  Then we use `longest_time * 1.1` (i.e. plus 10%) as the `buffer_time`.

Traceback or other info

* Djangae version: master@9043900ad485d84e9a2dbe3b54fcc66884bd533d

**Comment by Kazade** [comment]
I've started implementing this in branch calculate-buffer-time
