### ISSUE TITLE
PermanentTaskFailure: Requested setting AUTH_USER_MODEL

### ISSUE THREAD

**Issue by wittfabian** [potatolondon/djangae#1162]
I use defer to update my database and send emails in background (includes querying models). 
The defer method is called in a cronjob.
Sometimes I get the following error:

```
PermanentTaskFailure: Requested setting AUTH_USER_MODEL, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

```
Permanent failure attempting to execute task
Traceback (most recent call last):
  File "/.../google-cloud-sdk/platform/google_appengine/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/.../google-cloud-sdk/platform/google_appengine/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/.../google-cloud-sdk/platform/google_appengine/google/appengine/ext/deferred/deferred.py", line 153, in run
    raise PermanentTaskFailure(e)
```

* Djangae version: 0.9.11
* Django version: 1.11
* App Engine SDK version: 1.9.64
* Using Cloud SDK: yes (183.0.0)

**Comment by adamalton** [comment]
This looks like it's probably something to do with the way that you've configured your app / settings / django / paths / etc.

In `app.yaml`, do you definitely have the path `_ah/queue` being routed to your Django WSGI hander?  Like this: https://github.com/potatolondon/djangae-scaffold/blob/master/app.yaml#L9-L10

**Comment by wittfabian** [comment]
My code:
```
  - url: /_ah/(mapreduce|queue|warmup).*
    script: webpage.wsgi.application
    login: admin
```

**Comment by wittfabian** [comment]
The funny thing is, it only happens sometimes.

**Comment by wittfabian** [comment]
Is the "fix_path" required?

https://github.com/potatolondon/djangae-scaffold/blob/master/manage.py#L5

**Comment by davidwtbuxton** [comment]
Also make sure you are _not_ using `builtins: deferred` (because it will take precedence over the `webpage.wsgi.application` handler).

This would explain why you hit the bug only some of the time. Most of the time there is an idle instance that can run the deferred task, but occasionally the deferred task request will be the very first request to an instance, in which case your regular Django app startup doesn't happen.

**Comment by wittfabian** [comment]
I think that's it, thank you!
