### ISSUE TITLE
Research (re)-implementing the Search API

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#1197]
Issue description

The lack of a search API on the Python 3 runtime is a massive blocker for upgrading projects. It would be great if Djangae could provide a similar API in djangae.contrib.search that was built on the Datastore (or something else in Google Cloud).

This issue is to do some research about the architecture of Google's Search API - my instinct is it was built on the Datastore/BigTable - and see if such an app is feasible.

Steps to reproduce

 - Try to use the Search API on Python 3 :)

**Comment by davidwtbuxton** [comment]
I'd be interested to hear your thoughts on this. Ping me!

**Comment by Kazade** [comment]
djangae.contrib.search now exists in master. There are still some things to do including:

 - Exact matching: Needs to basically store "occurrences" of tokens in a ListField, and then use that when matching results after querying 
 - Stemming: Probably would mean adding a dependency on nltk, still thinking on this
 - Performance: See #1291 
 - AtomField (depends on #1291)

It does *not* try to replicate the full feature set of the GAE search API, but provides a reasonable syntax for common operations (e.g. AND/OR operators, quoted searches, field-specific searches)
