### ISSUE TITLE
Website quite out of date

### ISSUE THREAD

**Issue by adamchainz** [potatolondon/djangae#1199]
https://djangae.org/ seems to be based on a quite-old README, mentioning django 1.7-1.8 support and a version 1.0 release. It seems to be on GitHub pages, where the gh-pages branch was last updated September 2018: https://github.com/potatolondon/djangae/tree/gh-pages . Since the website doesn't have much content it might be best to redirect to the github readme now since that is kept up to date?

**Comment by Kazade** [comment]
Fixed :)
