### ISSUE TITLE
Consider adding more efficient support for pagination when using datastore-backed models

### ISSUE THREAD

**Issue by olibrook** [potatolondon/djangae#122]
On our project people have expressed an interest in adding better pagination support to Djangae when using the datastore backend. So far I have looked into the possibility of re-using what exists already in https://github.com/potatolondon/potatopage, but it looks like there are dependencies on `djangoappengine` in `potatopage`. Specifically, `potatopage` depends on the following in `djangoappengine.db.compiler`:

```
self.query._gae_cursor = query.GetCompiledCursor()
```

The compiler is the part of `djangoappengine` I am least familiar with. Maybe people can share their thoughts?

**Comment by Kazade** [comment]
I'm working on this in the pagination-api branch. This provides a class decorator: `@paginated_model` that allows you to define orderings you intend to paginate on, and generates fields dynamically for pre-calculating distinct ordered values. A new Paginator subclass makes use of these values to give you efficient pagination on the datastore without using cursors (which don't work on IN and != queries). This will be in djangae.contrib.pagination.
