### ISSUE TITLE
storage.Client does not work without project parameter

### ISSUE THREAD

**Issue by wittfabian** [potatolondon/djangae#1230]
**Issue description**

Using the Storage client returns the following error.
`Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application.`

Ref: https://github.com/potatolondon/djangae/blob/master/djangae/storage.py#L37

**Steps to reproduce**
```
from djangae.storage import CloudStorage

client = CloudStorage(bucket_name='my-bucket-name').client
```

Apparently the "project" parameter must be set for it to work. 
With `dev_apperser.py` the environment variable `GOOGLE_CLOUD_PROJECT` is set (default: test). Using this would be one possibility.

**Traceback or other info**

* Djangae version: master@abbafcda1536721c1713b1c4e8aea6d92ac19628
* Django version: 2.2.13
* Python version: 3.7.7
* App Engine SDK version: 1.9.91
* Using Cloud SDK: yes

**Comment by artoale** [comment]
Hey @wittfabian  - thanks for reporting this. I'm looking into this, will report back - thanks!

**Comment by artoale** [comment]
@wittfabian when this PR is merged, if you're calling `start_emulators` in your `./manage.py` hopefully it should be fixed :)
