### ISSUE TITLE
ServiceAccountCredentials is used in local development

### ISSUE THREAD

**Issue by flea89** [potatolondon/djangae#1258]
## Issue description
By using djangae.credentials.default() `djangae.credentials.ServiceAccountCredentials` is used in local development instead of `google.auth.default`

## Steps to reproduce
```py
from djangae.credentials import default
credentials = default()
```

Traceback or other info
*  master@ 79cb968

**Comment by davidwtbuxton** [comment]
Testing a function object rather than calling it and testing the output. The old bugs are the best.
