### ISSUE TITLE
Problem with `in` lookups on ForeignKey fields

### ISSUE THREAD

**Issue by olasitarska** [potatolondon/djangae#134]
Today I encountered this problem: when you try to do an `in` lookup on ForeignKey field, like that:

``` python
children = Child.objects.filter(foo='a')
parents = Parent.objects.filter(child__in=children)
```

You get this error:

```
TypeError: 'SubqueryConstraint' object does not support indexing
```

It only works when you make a `children` query into `list`.

**Comment by stucox** [comment]
I had a similar case, although it didn’t throw an error at all – just returned no items. Forcing the first query to be evaluated first with `list()` fixed it.

+1 for a clearer error message.

If Djangae could automatically perform 2 queries for this kind of thing that’d be useful, but obviously needs to be tossed up against potential for poor performance.

Does/should Djangae have a policy for when and how (whether to warn, etc) to support shortcuts which might potentially perform poorly?

**Comment by Kazade** [comment]
This is fixed now, the inner query will be evaluated first rather than resulting in an error
