### ISSUE TITLE
The `validate_certificate` argument is passed in as positional and named parameter to `urlfetch.make_fetch_call` due to our decorator adding the named one.

### ISSUE THREAD

**Issue by armirusco** [potatolondon/djangae#135]
Basically, we decorate `urlfetch.make_fetch_call` in here: https://github.com/potatolondon/djangae/blob/master/djangae/contrib/security/middleware.py#L100 

Now, when using the patched `urlfetch.fetch`, App Engine will pass `validate_certificate` along to `urlfetch.make_fetch_call` as a positional argument. Djangae's decorator adds `validate_certificate` as a keyword argument which means we end up with the same argument being passed in twice and Python getting annoyed. :( 

Hope that all makes sense, otherwise, please shout!

**Comment by Kazade** [comment]
@adamalton can we close this?

**Comment by adamalton** [comment]
Yeah, I reverted the code which caused this issue.  Closing.
