### ISSUE TITLE
Up the get-by-key limit to 1000

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#139]
According to the ndb code, the limit for getting by key is actually 1000, with put and delete still limited to 500. We need to fix that up because that makes everything better. We should use the setting in datastore_rpc.Connection.MAX_GET_KEYS

It would also be nice to remove the user-facing limit completely and to shard into batches of 1000. This is effectively what NDB does.

**Comment by olasitarska** [comment]
Closed by #387
