### ISSUE TITLE
Issue with multi-table inheritance and custom PKs

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#227]
If you have a concrete base model and another model subclassing it, and the subclass model has got a custom PK field, then things go wrong because Djangae forces the subclass model to have the same PK as the parent model.

**Comment by adamalton** [comment]
```
class Animal(models.Model):
    is_alive = models.BooleanField(deafult=True)

class Squirrel(Animal):
   name = models.CharField(primary_key=True)

ted = Squirrel.objects.create(name="ted)
print ted
```

will result in

```
TypeError: coercing to Unicode: need string or buffer, long found
```

being thrown from the model's `__repr__` method, because the value of the `CharField` gets set to the same value as the parent model's PK (which is an int).

We should find a way of detecting if set a custom PK on a model which is a child of a concrete parent model and throw some kind of meaningful `NotSupportError`.

**Comment by Kazade** [comment]
Moved to django-gcloud-connectors
