### ISSUE TITLE
UpdateCommand should not update entities which no longer match the query

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#263]
Suppose we have this situation:

```
obj = MyModel.objects.create(field1='a')
# that gets populated across all replicas of the Datastore, then a while later...
obj.field1 = 'b'
obj.save()

# then momentarily afterwards, this happens...
MyModel.objects.filter(field1='a').update(something=new_value)
```

Eventual consistency means that the `.update()` query may still see `obj`, even though it has been edited to no longer match the query.  So it may get altered by the `.update()` query when it shouldn't.

We can protect against this in our DB backend by making `UpdateCommand` smart so that it doesn't update entities if they don't actually match the query which fetched them.  Something like this:

```
class UpdateCommand(object):

    @db.transactional
    def _update_entity(self, key):
        caching.remove_entity_from_cache_by_key(key)

        try:
            result = datastore.Get(key)
        except datastore_errors.EntityNotFoundError:
            # Return false to indicate update failure
            return False

        # protect against updating entities which we get given which we shouldn't due to HRD
        if not entity_matches_query(result, self.select):
            return False
        ...
```

We can't do anything about the fact that `.update()` queries (like any other queries) might not get given entities which they should, but we can protect against them being given entities which they shouldn't.

**Comment by Kazade** [comment]
This is a high priority issue, it's an edge case, but we should never perform invalid queries
