### ISSUE TITLE
value_to_db_time is called twice when saving a TimeField

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#284]
Apparently until now no-one has used a TimeField with Djangae. When you do, and you save, value_from_instance calls `value_to_db_time` twice, firstly once from `get_db_prep_save` on the field class, and then again from `value_for_db` which is called by `get_prepared_db_value`.

The reason this bug shows with a TimeField is that the datastore has no support for times, so the time is converted to a datetime, then when `value_to_db_time` is called again, it tries to use `combine()` on a datetime, not a time. 

We could fix this by just making `value_to_db_time` a noop if the value is already a time, but the real issue though is that this should not be called twice so we need to figure out why it is and if it should be (maybe it should?)

I suggest looking at other database connectors.

**Comment by olasitarska** [comment]
https://github.com/potatolondon/djangae/pull/285
