### ISSUE TITLE
Make TravisCI run tests on both Django 1.6 and 1.7

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#292]
At the moment it's 1.6, when I merge 1-7-support it'll be 1.7. It would be nice to have both.

**Comment by pablorecio** [comment]
The nice way of doing this would be to avoid having a submodule and making pip to handle those dependencies. Probably also using tox https://pypi.python.org/pypi/tox.

Will work on that.

**Comment by Kazade** [comment]
Fixed!
