### ISSUE TITLE
Consider switching SelectCommand for GQL

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#306]
App Engine has it's own SQL-like language for select queries called GQL. Recently I've been considering whether we should replace SelectCommand with a generated GQL string. This would have the following advantages:

 - It's more like Django expects, we could pass around a string and params
 - It's potentially less code, we already have the WHERE tree from the DNF code, generating the GQL would be trivial
 - Django tests which count params returned from as_sql will work
 - It's a little less vulnerable to changes in Django

Disadvantages:

 - It requires rewriting a lot of code
 - We still need to maintain InsertCommand, DeleteCommand etc.
 - It may be harder to special case queries (e.g. QueryByKeys)

**Comment by olasitarska** [comment]
@Kazade is this something you're still considering, or should we close it? ;)

**Comment by olasitarska** [comment]
@Kazade says "kill it".
