### ISSUE TITLE
ForeignKey with 'self' causes a join and breaks

### ISSUE THREAD

**Issue by kirberich** [potatolondon/djangae#32]
```
class SampleModel(models.Model):
    related_field = models.ForeignKey('self', null=True, blank=True)

obj = SampleModel()
obj2 = SampleModel(related_field=obj)

obj.samplemodel_set.all()
```

Results in

```
*** NotSupportedError: 
The appengine database connector does not support JOINs. The requested join map follows
 {(u'simple_search_samplemodel', u'simple_search_samplemodel', 'related_field_id', u'id'): ('T2',), (None, u'simple_search_samplemodel', None, None): (u'simple_search_samplemodel',)}
```

I'll try and have a go at this later.

**Comment by alexedwardjones** [comment]
I seem to be having the same issue trying to use the default Auth setup, whenever I try to edit a user. Any idea's how I can get around this? It's turning out to be a bit of a pain in the ass.

    The appengine database connector does not support JOINs. The requested join map follows

     {(u'auth_user_groups', u'auth_user', (('user_id', u'id'),)): (u'auth_user',), (u'auth_group', u'auth_user_groups', ((u'id', 'group_id'),)): (u'auth_user_groups',), (None, u'auth_group', None): (u'auth_group',)}

**Comment by adamalton** [comment]
This looks like the same issue that used to exist in djangoappengine:
https://groups.google.com/forum/#!topic/django-non-relational/bFNQ_RDF9To

Hopefully with Djangae we can detect this and fiddle with the query to
remove the JOIN.

**Comment by juliocebrito** [comment]
Hello, I am trying to use Django admin when i clicking in a user then it happens

NotSupportedError at /admin/auth/user/6561971293913088/

The appengine database connector does not support JOINs. The requested join map follows

{(u'auth_group', u'auth_user_groups', ((u'id', u'group_id'),)): (u'auth_user_groups',), (None, u'auth_group', None): (u'auth_group',), (u'auth_user_groups', u'auth_user', ((u'user_id', u'id'),)): (u'auth_user',)}

djangae\db\backends\appengine\commands.py in execute, line 665

i found something here https://cloud.google.com/appengine/docs/java/datastore/jpa/overview

You can override the read policy and call deadline for an individual Query object. To override the read policy for a Query, call its setHint() method as follows:

        Query q = em.createQuery("select from " + Book.class.getName());
        q.setHint("datanucleus.appengine.datastoreReadConsistency", "EVENTUAL");

As above, the possible values are "EVENTUAL" and "STRONG".

To override the read timeout, call setHint() as follows:

        q.setHint("javax.persistence.query.timeout", 3000);

There is no way to override the configuration for these options when you fetch entities by key.

**Comment by adamalton** [comment]
Hi Julio/Alex,

I *think* that the problem is that you're trying to use the standard django.contrib.auth.models.User model, rather than the Datastore-friendly user models provided in djangae.contrib.gauth.datastore.models.

The standard django User model won't work on the App Engine Datastore because it's designed for a relational database which supports JOIN queries.

Did you follow the instructions about auth in the README?  If so, then possibly the only problem is that you're trying to view the django.contrib.auth.models.User model in the Django admin (/admin/auth/user/), rather than viewing the djangae.contrib.gauth.datastore.models.User (/admin/datastore/gaedatastoreuser).

The original issue reported by kirberich is still valid though.

**Comment by adamalton** [comment]
I think that actually the problem here is that you're using the standard
django.contrib.auth.models.User model, rather than one of the
djangae.contrib.gauth models.  See
https://djangae.readthedocs.org/en/latest/gauth/.

Adam
