### ISSUE TITLE
Prevent SSL redirect

### ISSUE THREAD

**Issue by morninj** [potatolondon/djangae#320]
How do I prevent the site from redirecting to https://? I need to use a custom domain for a small project, and I don't need SSL.

**Comment by kirberich** [comment]
You can set SECURE_SSL_REDIRECT to False in settings_live.py - there are a
few other options in there that might to be adjusted as well.

For more details, have a look at the django-secure docs on
https://pypi.python.org/pypi/django-secure

Cheers
Rob

**Comment by morninj** [comment]
Thanks—I tried that, but it didn't work. I tried removing django-secure entirely, but that didn't work either.

**Comment by kirberich** [comment]
Do your url entries in app.yaml have secure:always?

**Comment by morninj** [comment]
I *just* found that. Yes, `seucre: always` in `app.yaml` was the problem. Thanks for your help!

**Comment by jasoncartwright** [comment]
Just a small point, but HTTPS on App Engine apps is a really good idea - it means you get HTTP/2 for free, which can see a big performance improvement for modern browsers and more than half of all browser use.

http://caniuse.com/http2

I do understand that the extra cost & configuration pain can make this prohibitive for smaller projects :(

**Comment by morninj** [comment]
Good point. One caveat is that you can't use SSL on a custom domain unless you for Google Apps.
