### ISSUE TITLE
Google Files API Deprecation

### ISSUE THREAD

**Issue by samsniderheld** [potatolondon/djangae#343]
Hi I am using this platform for an app engine project that I am building. I just received an email from Google Cloud Platform that my app is using the Files API and that the API will be fully deprecated on August 4th. I have not enabled the api in my cloud console, but in storage.py you have:

from google.appengine.api import files

Do you have any plans to migrate to the Cloud Storage Client Library in the near future, or is the another file upload functionality that I am missing?

thanks.

**Comment by stucox** [comment]
Yeah this has been coming for a while.

3 options I can think of, which IMO Djangae should provide [storage backends](https://docs.djangoproject.com/en/1.8/howto/custom-file-storage/) for:

1. Cloud Storage (as you say) – good for big files / high throughput, but requires billing enabled.
2. Use [`create_upload_url()`](https://cloud.google.com/appengine/docs/python/blobstore/functions#create_upload_url) + a server-side POST to carry on using the Blobstore – good for medium-sized files (up to your memory limit), and backward-compatible (I think?)
    * Guess they might deprecate this too at some point…
3. Datastore, using a BlobProperty – up to 1MB per file

I’m gonna have a crack at a PR for option 2, as I have a large app I’d rather not have to migrate.

**Comment by Kazade** [comment]
I'm going to pick up option 1 a bit later, and I'll also add a migration task for switching any existing files.

**Comment by stucox** [comment]
@samsniderheld Luke’s [just merged](https://github.com/potatolondon/djangae/pull/346) an updated `BlobStorageBackend` which uses `create_upload_url()` under the hood.

I know you were specifically asking about Cloud Storage – we’re working on a backend for that – but do you fancy giving this a spin in the meantime? Should just be a matter of updating to latest HEAD.

**Comment by stucox** [comment]
@Kazade Not sure if I’d call this “complete” until we have a Cloud Storage backend too? And what about the Datastore one?

**Comment by stucox** [comment]
Raised a ticket for a Cloud Storage backend here: #370
