### ISSUE TITLE
AttributeError at / 'Exact' object has no attribute 'connector'

### ISSUE THREAD

**Issue by juliocebrito** [potatolondon/djangae#355]
Hi, When i install from pip install djangae raise this error, but i change djangae from GitHub so this work.

def process_node(node, connection, negated=False):
    if isinstance(node, tuple) and isinstance(node[0], Constraint):
        return ('LIT', parse_constraint(node, connection, negated)), negated
    if isinstance(node, tuple):
        return node, negated
    if node.connector == 'AND' or 'OR':

**Comment by Kazade** [comment]
I've just tagged v0.9.0 and pushed it to Pypi :)
