### ISSUE TITLE
Local task queues are broken when using deferred

### ISSUE THREAD

**Issue by pablorecio** [potatolondon/djangae#358]
It seems after https://github.com/potatolondon/djangae/commit/656686c4ae1bf0f1fd301f56eecfa9f7e3c48b4a deferred tasks stop working:

    WARNING  2015-06-01 15:44:42,572 request_info.py:541] 	Request dispatching is not supported with _LocalFakeDispatcher
    WARNING  2015-06-01 15:44:42,573 taskqueue_stub.py:1977] 	Task task32 failed to execute. This task will retry in 1.600 seconds

It seems is the last change:

    -    dispatcher = _create_dispatcher(configuration, options)
    -    request_data = wsgi_request_info.WSGIRequestInfo(dispatcher)
    -    # Remember the wsgi request info object so it can be reused to avoid duplication.
    -    dispatcher._request_data = request_data
    +    from google.appengine.api import request_info
    +    request_data = request_info._LocalRequestInfo()

As I tried to revert those, and it works, but then the blobstore stub doesn't seem to work on tests.

**Comment by Kazade** [comment]
So, I think we should revert the above change, and then add some code to the blobstore start/stop service to monkey patch whatever the LocalRequestInfo does different when dealing with the blobstore stub so that create_upload_url works properly offline.
