### ISSUE TITLE
Create a test blobstore service

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#365]
To circumvent the files API deprecation, we made the blobstore backend do a server-to-server post, which worked fine on live and while running the dev_appserver, but not while running management commands.

To fix this we added a blobstore service which starts with the sandbox, and shuts down when the dev_appserver starts. This works great for management commands. 

However, when running tests, even though we setup the blobstore stub.. I _think_ that we're writing persistent blobs in tests (this will need to be checked, I'm not 100% sure). If so, we should have a test blobstore service, one that is temporary and is started when tests start.

**Comment by davidwtbuxton** [comment]
Closing. New code should use the vanilla upload handler with the cloud storage backend, the files API was removed ages ago and cloud storage is much more useful than the blobstore as a storage platform.
