### ISSUE TITLE
Can you add some internal docs?

### ISSUE THREAD

**Issue by mnunberg** [potatolondon/djangae#368]
I'm working on a similar project, not for Appengine, but another database (Couchbase). Looking at your work, and it seems much better than the nonrel fork.

If possible, can you add some documentation and outline regarding how you discovered many of django's backend stuff, and how you've structured your own backend? This would help me and others having to effectively spend long hours reverse engineering code, as you've done this yourself already :)

**Comment by Kazade** [comment]
I'll see if I can throw something together :)

**Comment by Kazade** [comment]
I've just quickly hammered out a blog post, hopefully that will give you a good start: http://blog.kazade.co.uk/2015/06/how-djangaes-app-engine-datastore.html :)

**Comment by mnunberg** [comment]
Thank you!

I of course have some further questions. Shall I post them in this thread, or in the blog?

**Comment by Kazade** [comment]
Just ask on Gitter :) https://gitter.im/potatolondon/djangae
