### ISSUE TITLE
Add docs about storage

### ISSUE THREAD

**Issue by olasitarska** [potatolondon/djangae#419]
We don't have any docs about either Blobstore or Cloud Storage. Should we?

**Comment by chargrizzle** [comment]
Yes almost defiantly, I'm in the process of writing them

**Comment by olasitarska** [comment]
@chargrizzle @chargrizzle @chargrizzle :bear: :zap: 

just dumped them in the comment here maybe if you have anything, I'm happy to clean them up?

**Comment by chargrizzle** [comment]
Ok actually on it this time round
