### ISSUE TITLE
There is an edge case where unique constraints fail

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#425]
I've not worked out quite what it is, I'm documenting here just so that if it shows up again we may be able to better diagnose it. On production I've witnessed the following throw a MultipleObjectsReturned error (psuedo code):

    MyModel.objects.get_or_create(unique_together1="one", unique_together2="two", some_other_field="three")

Something similar to this was called in a deferred task, inside a transaction which was called inside a loop. Obviously, the correct usage of get_or_create is to use `defaults={}` for that final argument, but that shouldn't affect the unique markers. FWIW the two fields in the unique constraint were a CharField and a ForeignKey, and the additional field was another ForeignKey.

Interestingly, this was in the first retry of the task and the unique_together should've been unique to that task run... I'm not even sure when/how a dupe could have been created...

**Comment by olasitarska** [comment]
Think we fixed this one already...
