### ISSUE TITLE
Transaction decorators are not thread-safe

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#429]
In `djangae.db.transaction` we've got combined decorator/context manager classes, which store things (e.g. `conn_stack`, `transaction_started`) on `self`.

But if you use one of these decorators (e.g. `atomic`) like this...

```
@atomic
def my_function():
    fiddle_with_database_here()
```

then the class (`atomic` is a class) only gets **instantiated once**.  That means that all the calls to `my_function` are sharing the same instance, so - given that we're storing things on `self` - it's totally **not** thread-safe.

**Comment by Kazade** [comment]
So, they pretty much are in most cases, but there is at least one case where they are not (conn_stack) and a bunch of other issues (non_atomic doesn't work inside nested independent transactions, the code is ugly with too much recursion).

I'm going to refactor them, I'll close this ticket when I'm done!
