### ISSUE TITLE
Are you interested to integrate my django-denorm project into djangae?

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#434]
https://github.com/jacobg/django-denorm

I am willing to give over my project to djangae to own, integrate and enhance. Admittedly, it does not yet have test cases, good documentation, and there are several TODO's and FIXME's. There are a couple loose dependencies on djangoappengine that can be easily converted to djangae. But it's totally working, and I use it for my site.

**Comment by olasitarska** [comment]
Hi Jacob! 

Thanks for reaching out, but I think we're trying to keep Djangae smallish so that we don't increase the maintenance burden. Thanks for bringing our attention to your project though, will definitely give this a go soon!

**Comment by jacobg** [comment]
Sure no problem. Thanks
