### ISSUE TITLE
Suggestion: add total object count hint from datastore stats

### ISSUE THREAD

**Issue by jasoncartwright** [potatolondon/djangae#442]
E.g, say I have an object called Articles and want the total count I could use...

```
Articles.objects.count()
```

Which would return, using [datastore stats](https://cloud.google.com/appengine/docs/python/datastore/stats), the approximate number of entries. Of course, this count is delayed, and if filter() is used a NotSupported would have to be returned.

I guess you might not want to implement this because the count is often up to 24hrs old, and might be confusing.

**Comment by Kazade** [comment]
This actually did cross my mind a few days ago, but it's actually a terrible idea :)

The datastore statistics aren't only delayed by a little bit, they can be days out of date. Normally by the time they've been updated they're already old. Even worse, the use-case I think you are trying to solve is when there are too many entities to count quickly in the traditional way, but actually the more entities you have of a particular kind the more out of date the datastore statistics become!

There is one particular project that I've been looking at this week where there was a table of several million entities, and datastore stats says there's 400. We'd be better off replacing it with a pseudorandom number generator :p

If counting is too slow, then there are better ways to deal with it by moving it offline, either by keeping a counter, or by updating a cached datastore value in a background task.
