### ISSUE TITLE
ListField and SetField - new API

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#452]
In App Engine 1.9.25 they added the ability for the Datastore to store empty list values.  This means that we can improve the way that our `ListField` and `SetField` work, but doing so will involve backwards incompatible changes.  Allow Adam to explain...
### The Present

Currently, the Datastore cannot store an empty list in an Entity property.  So when you have a `ListField` or a `SetField` and you set the value to `[]` or `set([])` we store `None` in the Datastore.  This is because if we didn't store anything at all then the property wouldn't be indexed and so you wouldn't be able to query for objects where that field is empty.

This however creates 2 slight problems:
1. You cannot have a null-able `ListField` or `SetField`.  (Not really a problem.)
2. Because the Datastore indexes _each value_ in a list property, thereby allowing you to query on any of the values, a query for `MyModel.objects.filter(my_list=None)` will return objects where `my_list` is empty (stored as `None`) and will also return objects where `my_list` _contains_ `None` e.g. `[None, None]`.  We can't differentiate between the two.

Also, because of the fact that _each_ value in a list field is indexed, the ORM behaviour is slightly misleading, in 2 ways:
1. If you query for `.filter(my_list='sausage')` then you will return all objects where `my_list` _contains_ `'sausage'`.
2. If you query for `.filter(my_list=None)` then you will get back objects where `my_list` is `[]` (which is saved as `None` under the hood).  A `ListField` or `SetField` can never be set to `None` because they're not null-able (see above).
### The Future

Now that the Datastore can store empty lists, this allows us to improve things.  Here is the way that we want things to eventually work:
- `ListField` and `SetField` will still not be null-able.  If we allowed them to be nullable then querying for a value of `None` would still be ambiguous (see problem _2._ above).
- To find objects where the list/set field is empty, you will use `.filter(my_list__isempty=True)`.
- To find objects where the list/set field is **not** empty, you will use `.filter(my_list__isempty=False)`.  Under the hood this will translate to `.exclude(my_list=[])`.
- To find objects where the list/set field contains a specific value, you will use `.filter(my_list__contains='sausage')`.
- Doing `.filter(my_list__contains=['sausage', 'carrot'])` will not be supported because it's ambiguous.  Does it filter for objects which contain `'sausage'` **and** `'carrot'`, or does it return objects which contain either?
- Doing `.filter(my_list='sausage')` will not be supported because it's misleading (it's actually a `__contains` query, but doesn't look like one (see misleading ORM behaviour _1._ above).
- Doing `.filter(my_list=['sausage', 'carrot'])` will not be supported because it can't be supported!  The fact that the Datastore indexes _each_ value means that equality filters on a list/set field are actually `__contains` filters, and therefore this query would also return objects where `my_list` is `['sausage', 'carrot', 'badger']` and other such things.  We can't filter for an exact match on the whole list.
### The Journey

So how do we move from the present state to the bright and beautiful future?  We will need:
- Courage.
- To do this before we release Djangae 1.0, so that we don't immediately have a backwards incompatible change.
- A migration thing which can migrate people's old data (e.g. `my_list=None`) to the new structure (`my_list=[]`).
  - To do that we should probably implement the migrations stuff first.  See #438.

**Comment by olasitarska** [comment]
"Courage" :muscle:

**Comment by davidwtbuxton** [comment]
Possibly related to this is how sets are represented in JSON.

Personally I think it makes most sense to serialize a Python set as a JSON array. This does mean that you cannot round-trip Python -> JSON -> Python without knowing that the incoming JSON data is supposed to be represented as a set. But I think the advantage for whoever is consuming the JSON outweighs the burden on the back-end.

**Comment by Kazade** [comment]
To be fixed for Djangae 2.x (see https://github.com/potatolondon/django-gcloud-connectors/issues/13)
