### ISSUE TITLE
Add lazy query evaluator for Datastore

### ISSUE THREAD

**Issue by mrfuxi** [potatolondon/djangae#463]
Currently Django evaluates whole queryset when tries to iterate over it.
That's not always necessary / good idea.

Code below evaluates whole queryset before even getting into the body of the loop.

```
for o in queryset:
    break
```

While this example does not make a lot of sense, imagine you actually have sorted queryset and only needs to process some number of objects and break (adding second not equal condition)

**Comment by adamalton** [comment]
The lazy evaluation is what should happen when you do `queryset.iterator()`, right?

I *think* that full evaluation is the right thing to do when you just do `for` on it.  But I guess we should implement the lazy iteration for the `.iterator()` method.

**Comment by Kazade** [comment]
That's not what the iterator() function does apparently - Django done goofed

**Comment by Kazade** [comment]
Not much more we can do about this, this is all down to Django. The App Engine RPC does batching so that helps a little.
