### ISSUE TITLE
urllib2.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by sikor80** [potatolondon/djangae#464]
I'm following your setup from here https://github.com/dannymilsom/djangae-blog and I'm able to run static django pages on GAE without any issues. The problems start when I try to use "djangae.db.backends.appengine" as I want to have some basic data stored in DB. I basically don't know how to get my django models synced to the datastore in GAE. When I follow this doc here http://djangae.readthedocs.org/en/latest/sandbox/, I end up using "./manage.py --sandbox=remote makemigrations" but that gives me nasty error like this:
https://gist.github.com/sikor80/334241b17b44b94b95c5

Would you be able to help me with this? Google or stackoverflow gives me nothing :(

And additionally when I try to sync my models locally and get this error https://gist.github.com/sikor80/879b5df7fd8ff6d42f88, my models are very simple as shown https://gist.github.com/sikor80/1c294b3339a2ff91c343

**Comment by adamalton** [comment]
Hi Sikor,

Short answer: you don't need migrations; the Datastore doesn't really have "tables", instead it has "kinds" but these only get created when you save objects to the DB.  So just start creating objects, you don't need to create the "tables" first.

Longer answer: #438.

**Comment by kittuov** [comment]
I'm having the same problem but i'm using cloud sql so it is mandatory for me. i'm using scaffold app with little changes and sql database for remote.

**Comment by allofthesepeople** [comment]
@sikor80 from the 404 error in the title, did you set the route in `app.yaml` and deploy?

Default requirement is:
```
builtins:
- remote_api: on
```
as per https://cloud.google.com/appengine/docs/python/tools/remoteapi#enabling_remote_api
