### ISSUE TITLE
PaginationOrderingRequired is being thrown when initializing a Paginator object with a queryset that doesn't have order_by specified.

### ISSUE THREAD

**Issue by owad** [potatolondon/djangae#465]
Basically when you do this:

```
event_list = Event.objects.order_by("-modified")
paginator = Paginator(event_list, 25, readahead=10)
```

It's all fine, but this isn't even though Event class has a Meta.ordering set to ["-modified"]:

```
event_list = Event.objects.all()
paginator = Paginator(event_list, 25, readahead=10)
```

**Comment by scottg1989** [comment]
After looking into this, it looks like we now check for the ordering specified on a model's `_meta`, when no custom ordering has been specified in the query set. I've added a test to prove this.

@owad hopefully I've properly understood what behaviour you we're expecting here?
