### ISSUE TITLE
More efficient entity caching

### ISSUE THREAD

**Issue by mrfuxi** [potatolondon/djangae#474]
Currently often entities are cached one by one, even when whole set is available.
That leads to situation when mc calls are actually slowing down `get` queries.
Most noticeable in `QueryByKeys`

**Comment by mrfuxi** [comment]
In [1]: from django.core.cache import cache

In [2]: cache.get_many(['a', 'b'])
Out[2]: {}

In [3]: cache.set('a', 1)

In [4]: cache.get_many(['a', 'b'])
Out[4]: {'a': 1}

**Comment by grzes** [comment]
Brilliant, ignore me.
