### ISSUE TITLE
Wishful Thinking - Change License to BSD and changes to copyright details  

### ISSUE THREAD

**Issue by techdragon** [potatolondon/djangae#488]
This project is super awesome, you guys are super awesome, and I'm not trying to start some GPL vs MIT/BSD, the CLA is steal your soul, or Vim vs Emacs type flamewar. Everything that follows is meant to be a constructive addition with the simple goal of, somehow, theoretically, making the world a better place, in some way, no matter now small it may be. Any malice, insult, negative impressions or other negative outcomes were not my original intent. /emotional-protection-boilerplate

The facts as they stand: 

Djangae is: 
 - Awesome work by a bunch of very talented people.
 - MIT licensed
 - All contributions welcome in the form of a pull request without any additional effort.
 - Has a copyright notice assigning the copyrights to code to: 
   - The primary author
   - All other contributors
 - Extending the ways Django can be used
   - Creating a _**compatible**_ Django database backend that enables a 'NoSQL' database to be used to run what is otherwise 'vanilla' django. No django-nonrel fork required.
 - Is teaching at least a few people who contribute to the project, quite a lot more about the structure, design and workings, of Django's miscellaneous database related layers and ORM, than many Django developers will ever need to know.
 - Is arguably the current 'best' example of how to integrate Django with a 'non relational data store' yet developed.
 - Is significantly valuable as a starting point from which other developers can just experiment or seriously attempt to develop other additional database backend drivers for Django.

Django is: 
 - Awesome work by a large bunch of very talented people.
 - BSD licensed
 - Requires contributors to sign a [Contributor License Agreement](https://www.djangoproject.com/foundation/cla/faq/)
   - This helps the Django Software Foundation do what it does.
     - They seem to be doing a pretty good job. :+1: 
 - Unable to work properly with 'NoSQL' databases.
    - not counting the various forks, custom model packages, etc.
 - Not opposed to supporting 'NoSQL' databases.
   - Willing to consider changes that affect the functionality of the existing Databases in order to make new drivers possible if it won't break the existing databases - My [issue ticket](https://code.djangoproject.com/ticket/25265) wasn't considered rejected. I'm still pleasantly surprised by this. 
 - Definitely has a segment of the Django community that desires support for 'NoSQL' databases of several different kinds.
 - As an ongoing software development project, and as a healthy developer community around an open source framework, Django needs more developers who understand its database related layers and ORM.
   - They are few and their task is significant.  
   - The existing developers are wonderfully brilliant and more than happy to talk to you about this code if you have the time and if they understand the part you want to talk about.
     - I discovered this first hand at PyCon AU this year. :smile:

So what does this mean:

I know its very wishful thinking but since this is the sort of thing that is best done sooner rather than later, it would be pretty amazing if the project could change the license to BSD, and get some sort of solution to the issue of copyright that would enable the code from this repo to wind up 'upstream', regardless of how the code gets there, or where exactly 'there' is. If this License and the copyright 'issue' can't be resolved, then anyone who wants to try and develop any sort of non relational database engine for Django, can't take advantage of the hard work you guys have put in if they want to try and get their work upstreamed under the django project umbrella. There is a high barrier to entry for understanding the internals of the Django ORM, projects like this one can help lower that barrier if there is more 'cross pollination' between Django core developers and the people working on things like Djangae. When I say 'like Djangae', I pretty much mean Djangae, and projects forked from Djangae, there are exceedingly few other libraries out there that are stable enough to really learn from, and under active development targeting Django >=1.8 (Dealing with the changes from adding migrations and from formalising the Meta API).  

The sort of very significant work on Database libraries and/or ORMs that Djangae is doing right now and that other libraries have done in the past, can be very hard work, and I just had to ask if its possible. Making awesome software, like a RethinkDB backend for Django, is the sort of thing I care about enough to spend a while writing a long GitHub issue like this, to try and hopefully get my thoughts across.

I'm not expecting anything magic. I just wanted cross my fingers for luck, and try to start a discussion in the hopes it goes somewhere rewarding.

**Comment by Kazade** [comment]
Hi!

As the MIT license is actually more liberal than the BSD license used by Django, and MIT is compatible with BSD, I'm not sure what the benefit in changing the license would be?

**Comment by techdragon** [comment]
I'm closing this one because I've come to the conclusion its the wrong approach. 
It would be better to start a new separate package with the intent of building such common functionality in there, and collaborating around the new separate library designed with reuse in mind.
