### ISSUE TITLE
accept transaction options to atomic decorator

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#490]
e.g., # of retries

**Comment by Kazade** [comment]
Not supporting retries in `atomic()` is a conscious decision for a number of reasons:

 1. `atomic()` is a context manager as well as a decorator, you can't loop retries in a context manager 
 2. Automatically retrying transactions can obscure contention on your entities - which can come back to bite you on production when suddenly it's busy and your retry count isn't enough. By not retrying by default, it allows you to catch this situation and consider restructuring your data, or, if retrying really is the answer, then wrapping that code in a loop
 3. Django's `atomic()` doesn't retry

That said, I'm willing to accept a patch that adds an `atomic_with_retries(retry_count, **kwargs)` decorator which calls the wrapped function inside the atomic() context manager, in a loop.

**Comment by jacobg** [comment]
Thanks, that makes sense. I'm porting an old app that used increased retries due to some contention issues in the past. I'll try to use the vanilla atomic, and see if the contention exists anymore. It may be gone now. A lot has changed since they were originally put in.

Closing this issue for now.
