### ISSUE TITLE
add support for Django BinaryField

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#491]
It looks like there's just two simple changes necessary to support BinaryField:

in db/backends/appengine/base.py DatabaseCreation.data_types, add dict item:
```python
'BinaryField':                'bytes'
```
in db/backends/appengine/dbapi.py add the following function:
```python
def Binary(val):
    return val
```

If I make a pull request, will you accept it?

**Comment by chargrizzle** [comment]
Of course, if you can throw in a couple tests as well for good measure!

**Comment by olasitarska** [comment]
I think this has been fixed by now.

**Comment by jacobg** [comment]
Thanks
