### ISSUE TITLE
Using the admin in a appengine modue with XXXX.yaml file

### ISSUE THREAD

**Issue by urit** [potatolondon/djangae#498]
I want to Use the admin in a appengine modue with XXXX.yaml file
now the name of the yaml file is app.yaml only, it not enable me to use it in an appengine module with its own named yaml file.

please add a setting.py varuable like DJANGAE_APP_YAML_LOCATION but with a whole file name
ie DJANGAE_YAML_FILE_PATH
Thanks

U

**Comment by Kazade** [comment]
Such a setting exists (although it needs documenting): settings.DJANGAE_ADDITIONAL_MODULES which is a list of paths to yaml files for different modules.

**Comment by urit** [comment]
the find_project_root() function in the util use the DJANGAE_APP_YAML_LOCATION only,
so if I have a module with a different yamale file name it does not work

**Comment by Kazade** [comment]
If you add the list of *additional* module yaml files (e.g. the default module uses the find_project_root setting) to the DJANGAE_ADDITIONAL_MODULES setting, then these will be passed down to the dev_appserver and will run instances for them.

**Comment by urit** [comment]
Yes but if I run the app from the googleAppLauncher the find_project_root will not find the app.yaml as it is not in the path.

**Comment by olasitarska** [comment]
Djangae is not gonna work when run with GoogleAppLauncher -- you need to use a `python manage.py runserver` command that fixes the path. GoogleAppLauncher uses devappserver directly, and we can't fix the path in this scenario.

**Comment by urit** [comment]
you can do it in the wsgi.py

**Comment by olasitarska** [comment]
We would be happy to review your pull request for that. However, I think `python manage.py runserver` is a good enough solution for this problem.

Djangae's goal is to make Django work on App Engine in a *Django way* not *App Engine way*, hence why we've done it this way.

**Comment by Kazade** [comment]
Also, by only doing path manipulation in wsgi.py you prevent management commands (migrate etc.) from working correctly, also the remote sandbox won't work.
