### ISSUE TITLE
mapreduce: need finalized callback

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#509]
DjangaeMapperPipeline.callback is not the final callback to be made. DjangaeMapperPipeline.finalized is, as it contains the output counters, whereas the output counters have not yet been filled when calling DjangaeMapperPipeline.callback.

Also, it'd be great for either callback to the task to include the job name.

**Comment by chargrizzle** [comment]
https://github.com/potatolondon/djangae/pull/536
