### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by matto1990** [potatolondon/djangae#514]
What is the plan for the next release? This doesn't have to be a 1.0 release, however there have been over 450 commits to the project since 0.9.1, so it does seem like one is due soon.

Currently I am using the HEAD version of Djangae in my project. Is this recommended currently or should I instead be using 0.9.1?

**Comment by olasitarska** [comment]
Good point, we've talked about this for a bit and with support for 1.9 around the corner (which also means dropping support for Django 1.7), this is probably the right time to do it.

**Comment by matto1990** [comment]
Perfect! So when #504 is closed there will likely also be a tagged release on PyPI?

**Comment by olasitarska** [comment]
We're going to make one today/tomorrow with current master (for those who are gonna want to stay on Django 1.7, for example), and then next one as soon as #504 is done.

**Comment by olasitarska** [comment]
And this is now done!

**Comment by matto1990** [comment]
Thanks!
