### ISSUE TITLE
UpdateCommand._update_entity should have option to bypass transaction

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#518]
It'd be great to have a "fast update" option to bypass the transactional behavior of updates. I have scenarios where I don't care about caching or constraints, and don't want to be tied down by doing a transactional update.

**Comment by Kazade** [comment]
Do you mean this?

```
    @db.transactional
    def _update_entity(self, key):
```

If so, that transactional isn't there for caching or constraints - trust me you want this one :)

Without that transactional per-entity update you'll end up losing data randomly when two requests try to save the same object at about the same time. Djangoappengine had the same transactional mechanism in place.

That said there are probably performance improvements to be made here. I'll think about what we can do to improve the situation for bulk updates and what guarantees we should make about them.

**Comment by jacobg** [comment]
Thanks Luke. I trust you. It's just that I'm doing version traffic splitting of my app between the old djangoappengine version, and the new djangae port; and I'm seeing that on certain requests which do a single write of an entity under contention, the djangae version is much slower. The djangoappengine version completes the entire request in a few hundred ms, whereas djangae can take 1.5 seconds. Do you see possibly the area for improvement?

In this scenario, I actually would like to abort the save immediately if there is already a transactional lock on the entity / entity group, as I know that the other request holding the lock will make the same change. How would you suggest I accomplish that behavior with the djangae db backend?

**Comment by Kazade** [comment]
Just to confirm, do you have constraints enabled for that particular model?

**Comment by jacobg** [comment]
No, it's turned off globally in settings.py:

```python
#
# Turn off Djangae cache, because it causes test cases to fail where
# model instances are tweaked in the test case. I need to understand this
# setting better before considering to turn it on.
#
DJANGAE_CACHE_ENABLED = False

#
# Turn off constraint checks, because it significantly hurts performance.
#
DJANGAE_DISABLE_CONSTRAINT_CHECKS = True
```

**Comment by Kazade** [comment]
Could you give me example of exactly the ORM queries that you are running?

**Comment by jacobg** [comment]
Do you mean the queryset that looks up the model? Or the sql for the update?

There a couple models that have this issue. The simpler one does a query using:

```python
mymodel = MyModel.objects.get(token=token) # token is a CharField
# update a bunch of mymodel fields
mymodel.save()
```

**Comment by Kazade** [comment]
I've spent a while looking through the code, and once you disable constraints and caching, I can't see anything different between what Djangae does and what Djangoappengine does. Are you sure the performance is lost at the point of save and not elsewhere?

**Comment by jacobg** [comment]
Sorry for the delay. I did not have a change to follow up on this message until now.... The difference I see with DjangoAppengine is that Djangae does several memcache calls inside the transaction via `caching.add_entities_to_cache()`. Perhaps those several calls are triggering contention. Should this entity caching going on even though I have set `DJANGAE_CACHE_ENABLED=False`?

**Comment by Kazade** [comment]
Sorry for the late reply, I missed the notification. Yes, the code was broken! It was setting the cache regardless! I've created #574 to fix this.
