### ISSUE TITLE
manage.py RuntimeError

### ISSUE THREAD

**Issue by timkofu** [potatolondon/djangae#539]
Running manage.py is throwing the following exception:

    Traceback (most recent call last):
      File "./manage.py", line 8, in <module>
        from djangae.core.management import execute_from_command_line
      File "/opt/anaconda2/lib/python2.7/site-packages/djangae/core/management/__init__.py", line 11, in <module>
        "storage_path": os.path.join(find_project_root(), ".storage"),
      File "/opt/anaconda2/lib/python2.7/site-packages/djangae/utils.py", line 70, in __call__
        value = self.func(*args)
      File "/opt/anaconda2/lib/python2.7/site-packages/djangae/utils.py", line 106, in find_project_root
        raise RuntimeError("Unable to locate app.yaml. Did you add it to skip_files?")
    RuntimeError: Unable to locate app.yaml. Did you add it to skip_files?

(line 85 in utils.py is my main suspect, as _ _file_ _ could be returning utils.py path, but manage.py's is the one desired?)

app.yaml is in the same directory as manage.py
dev_appserver serves up the site without errors.
I'm on version 0.9.2

**Comment by moggers87** [comment]
Where is `manage.py` exactly?

Djangae expects to find itself in a directory within your project as it needs to get uploaded when deploying. (This is why `find_project_root` is looking at `__file__` and then iterating up over parent directories)

Alternatively, you can set the environment variable `DJANGAE_APP_YAML_LOCATION` to where your `app.yaml` and `manage.py` are.

**Comment by timkofu** [comment]
I had used the GAE's [vendoring in](https://cloud.google.com/appengine/docs/python/tools/libraries27?hl=en#vendoring) method to install Django and Djangae.

Manually puting Django and Djangae into a folder and manipulating the sys.path in (wsgi,manage).py worked.

**Comment by olasitarska** [comment]
Great!
