### ISSUE TITLE
Add a view to delete old sessions

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#549]
As per the [Django docs](https://docs.djangoproject.com/en/dev/topics/http/sessions/#clearing-the-session-store) old session data should be cleared out regularly.

We should provide a view in `djangae.views` which does this.  Then in [djangae-scaffold](https://github.com/potatolondon/djangae-scaffold) we should add a cron job that calls this view.

**Comment by LuRsT** [comment]
@adamalton, I don't understand the need for a view to do this. Couldn't it be done by just calling [clearsessions](https://docs.djangoproject.com/en/dev/ref/django-admin/#django-admin-clearsessions) on [djangae-scaffold](https://github.com/potatolondon/djangae-scaffold)?

**Comment by moggers87** [comment]
@LuRsT on App Engine, cron jobs are just URLs that get called at a specified time. [Docs](https://cloud.google.com/appengine/docs/python/config/cron).

**Comment by LuRsT** [comment]
Oh right, thanks for your help @moggers87! :smiley:
