### ISSUE TITLE
Over encoded default value in JSONField

### ISSUE THREAD

**Issue by mrfuxi** [potatolondon/djangae#558]
With `dumps` or `'{}'` default value in DB looks like it's passed though dumps twice and then returns as a `string` rather than a `dict`.

Once object is saved value in DB looks ok and is returned as a `dict`

**Comment by adamalton** [comment]
Can you explain this a bit more?

**Comment by mrfuxi** [comment]
Well, by default you have `'"{}"'` in database rather than `'{}'`. Once you do save you will get the later one into DB.

**Comment by adamalton** [comment]
Ah, I see.  Is the fix just to use `JSONField(default={})` instead of `JSONField(default="{}")`?

**Comment by mrfuxi** [comment]
I think that problem is here: https://github.com/potatolondon/djangae/blob/master/djangae/fields/json.py#L82:L85

Removing `dumps` and replacing `'{}'` with `{}` should do the trick

**Comment by adamalton** [comment]
Well, clearly you should add a test and a fix and make a PR :stuck_out_tongue:

**Comment by mrfuxi** [comment]
Well, the hardest part is to add some reasonable test

**Comment by Kazade** [comment]
This has  been fixed since being reported
