### ISSUE TITLE
JSONField returns floats as strings after a second save

### ISSUE THREAD

**Issue by kirberich** [potatolondon/djangae#560]
JSONField parses floats in the datastore as decimals. DjangoJSONEncoder makes decimals into strings before passing them to json.JSONEncoder (because Decimal isn't json-serializable), which is why ultimately, after an extra save, JSONFields will return float values as strings.

This would easily be fixed by removing parse_float=Decimal in fields/json.py, but I'm guessing that's there for a reason?

Here's some low-level code that reproduces the behaviour:

```
In [67]: from djangae.fields.json import dumps, loads

In [68]: dumps({'test': 0.1})
Out[68]: '{"test": 0.1}'

In [69]: loads(dumps({'test': 0.1}))
Out[69]: {u'test': Decimal('0.1')}

In [70]: dumps(loads(dumps({'test': 0.1})))
Out[70]: '{"test": "0.1"}'

In [71]: loads(dumps(loads(dumps({'test': 0.1}))))
Out[71]: {u'test': u'0.1'}
```

**Comment by Kazade** [comment]
I dunno, this field came from another library - if you think the behaviour is incorrect send a PR ;)

**Comment by kirberich** [comment]
Sure, if we don't have a good reason for having Decimal there I'll rip it out and see if it makes any tests break.
