### ISSUE TITLE
Files created in Google Cloud Storage should inherit permissions by default

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#571]
At the moment the CloudStorage storage backend defaults to creating new files with an explicit ACL of 'private', which results in the bucket owner being the only one who can access the file, even if the bucket permissions allow others to read files.

It would be better to have uploads use the default Google Cloud Storage permissions.

**Comment by Kazade** [comment]
Fixed!

**Comment by davidwtbuxton** [comment]
I totally forgot to reference this ticket in the pull request for #572 .
