### ISSUE TITLE
values/values_list shouldn't trigger a projection query, only/defer should

### ISSUE THREAD

**Issue by ghost** [potatolondon/djangae#58]
I  originally implemented the connector to do a projection query if the list of fields was specified (e.g. values()) but, actually that's a bad idea. Projections don't return results if an instance isn't indexed with one of the queried fields and values() shouldn't give different results to .all(). As values() is a common call this could be an easy silent mistake.

It's probably a better idea to optimize the only/defer case to use projection queries, we can document that fields must be indexed when using only/defer and as only() is used for performance only it's a better match. 

To clarify, values() and values_list() should never generate a projection query, only()/defer() should if possible.

**Comment by Kazade** [comment]
I'm going to do this... although it will mean that people upgrading who currently use:

    Model.objects.values_list("pk", flat=True)

Will need to change that to:

    Model.objects.only("pk").values_list("pk", flat=True)

To benefit from the keys-only optimisation.

**Comment by Kazade** [comment]
OK, it turns out that values/values_list wipe out the only/defer calls. So we have no option than to leave things how they are :/
