### ISSUE TITLE
AppEngineUserAPIBackend raises TypeError, should return None if user not recognized

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#592]
If you use the `djangae.contrib.gauth.datastore.backends.AppEngineUserAPIBackend` backend, it raises TypeError if the user cannot be authenticated. It should return None.

Django's `django.contrib.auth.authenticate` function inspects the backend's method signature to work out what credential arguments it accepts, and catches TypeError there.

[It _used to_ just call the backend's authenticate method with **kwargs and then treat a TypeError as equivalent to returning None][old]. But since Django 1.7 [it will fail if the backend raises TypeError][new].

[old]: https://github.com/django/django/blob/stable/1.6.x/django/contrib/auth/__init__.py#L43
[new]: https://github.com/django/django/blob/stable/1.7.x/django/contrib/auth/__init__.py#L48

**Comment by davidwtbuxton** [comment]
Also it would be good to make the backend naming consistent. There is:

- djangae.contrib.gauth.sql.backends.AppEngineUserAPIBackend
- djangae.contrib.gauth.datastore.backends.AppEngineUserAPIBackend
- djangae.contrib.gauth.backends.AppEngineUserAPI

The last one is effectively the datastore backend renamed (and sub-classed, but adds nothing). Can we remove it?

**Comment by adamalton** [comment]
Ah, right, I didn't know that Django had changed the way it did this.

> The last one is effectively the datastore backend renamed (and sub-classed, but adds nothing). Can we remove it?

Yes.  That's just a backwards compatibility hangover from before we split things into the separate `datastore` and `sql` apps.  We should kill it before the 1.0 release.
