### ISSUE TITLE
Simplify settings for auto-creating Django users when using the App Engine authentication backends

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#595]
Hello,

The `DJANGAE_FORCE_USER_PRE_CREATION` and `DJANGAE_ALLOW_USER_PRE_CREATION` settings control whether the AppEngineUserAPIBackend allows a _new_ user to authenticate if there is not a corresponding Django user in the database.

It would be nice to simplify the logic for whether a Django user is created and whether the user is allowed access, and to have a more obvious name for the setting(s) that govern this behaviour.

Instead of checking 2 settings, we could have a single setting, something like `DJANGAE_AUTO_CREATE_USERS`. This new setting would default to `False`.

The new logic could be:

- If the user is not logged in with Google Auth then **deny access**.
- If the user is logged in with Google Auth then:
  - If there is no existing Django user and if `AUTO_CREATE_USERS=False` then **deny access**.
  - If there is no existing Django user and if `AUTO_CREATE_USERS=True` then create a new Django user and **allow access**.
  - If there is an existing Django user then update the email address and **allow access**.

One thing missing from the above proposed logic is what should happen if `AUTO_CREATE_USERS=False` and the Google Auth user is an App Engine admin. I'm guessing it would be nice to always create a Django users for App Engine admins and allow access.

It would be nice to respect the existing force/allow settings for backward compatibility, although the existing logic is a little screwy and would be fiddly to maintain exact parity with the proposed new logic (mostly because _if_ there is not an existing Django user **and** `DJANGAE_FORCE_USER_PRE_CREATION=True` **and** the user is not an admin _then_ access is denied).

Also I've no idea if Django then checks the `is_active` flag on an authenticated Django user. Is that something Djangae's authentication backend has to check itself? My assumption is that Django does that after a backend returns a Django user instance.

**Comment by davidwtbuxton** [comment]
Looking at the current implementation, it also does a little dance if there is an existing user with a matching email address but a different user id (stored as the username on the Django user). In that situation it removes the email address from the existing user and then creates a new user with the same username as the existing user (and with the new email address).

I don't see how that can work because GaeAbstractBaseUser.username is unique.

Assuming that logic doesn't work, I think it makes sense to deny access if there is an existing user with a matching email address but a different (non-null) user id.

**Comment by olasitarska** [comment]
has been resolved now! 🎉
