### ISSUE TITLE
Passing --require_indexes=yes doesn't set the option on dev_appserver

### ISSUE THREAD

**Issue by nealedj** [potatolondon/djangae#614]
Run `manage.py runserver --require_indexes=yes`.

`datastore_require_indexes` (devappsever2.py:901) is set to `False`

**Comment by sleepyjames** [comment]
Still seeing this issue too. I think it stems from the fact we try to add these extra options within the `runserver` command, which is too late, as by this point the datastore stub has [already been created by the sandbox](https://github.com/potatolondon/djangae/blob/master/djangae/sandbox.py#L173).

**Comment by nealedj** [comment]
Should be fixed by #688 when it gets reviewed again.

**Comment by sleepyjames** [comment]
Ha, nice one :-)
