### ISSUE TITLE
Provide Cloud Storage functionality to replace/complement Blobstore

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#63]
The Blobstore files API is deprecated in favour of Google Cloud Storage.  Although not all of the Blobstore functionality is deprecated, and the two kind of interact.

I need to do some more reading of the docs to understand where the line is drawn, but we should consider adding things into storage.py to allow easy use of GCS-based Blobstore things.

**Comment by stucox** [comment]
This is superseded by #343 / #346 / #370.
