### ISSUE TITLE
Run Django master test via Travis daily

### ISSUE THREAD

**Issue by olasitarska** [potatolondon/djangae#630]
We wanna setup Travis in a way that it runs Djangae master against Django master tests once a day, and reports to our Slack so we can keep an eye on future Django release

**Comment by moggers87** [comment]
Via https://github.com/travis-ci/travis-ci/issues/582:

https://nightli.es/

**Comment by olasitarska** [comment]
Useful! Thanks @moggers87

**Comment by olasitarska** [comment]
Ok, so it's easy to trigger a daily build: Travis has API for that, and we can have a tiny cron job that does that. 

It's not easy to make Travis run a different subset of tests/environment, because when triggering that build, we can pass two pieces of info: branch, and build message. Message is not passed anywhere, but `branch` is. This is what we gonna use. 

- We need to add `DJANGO_VERSION=master` environment 
- We need to add `nightly` branch
- We need to add a preinstall script that will merge master into nightly branch if `TRAVIS_BRANCH` env variable equals `nightly`
- We need to add a custom bash script that will run the tests. This script will skip running tests on DJANGO_VERSION=master environment if TRAVIS_BRANCH == 'nightly'. 
- We need to modify the settings.py of testapp to set all Django apps as TO_TEST when TRAVIS_BRANCH == 'nightly'. 
- Lastly, we need to have a tiny App Engine app that will trigger a nightly build every 24 hours. 

And I think that could just work :)
