### ISSUE TITLE
djangae.storage.CloudStorage as storage backend breaks images

### ISSUE THREAD

**Issue by LilithWittmann** [potatolondon/djangae#662]
I try to save images via the django image field by using djangae.storage.CloudStorage as default storage. But after upload all images are broken (looks like the image header is missing or something). When I test it locally with the django development server it works. Im using Django 1.8.8 and djangae 0.9.2. Attached you find an example image before and after the upload to cloud storage. Do you have any ideas what I'm doing wrong?

![appengine_saved_image](https://cloud.githubusercontent.com/assets/891030/15141962/06ebd3ac-16a3-11e6-82b8-57cdd012ec43.jpg)
![appengine_uploaded_image](https://cloud.githubusercontent.com/assets/891030/15141965/0bf116dc-16a3-11e6-95a5-5e36d57d844d.jpg)

Also it would be great if there would be an example how to use `djangae.storage.serve_file`.

**Comment by Kazade** [comment]
Could you test with latest master and let me know if the problem still persists?

**Comment by Kazade** [comment]
OK, I have a theory! 

Are you by any chance validating the file is the correct format by checking the first part of the file (e.g. the first 380 bytes) or doing anything which may partially read the file before it is saved?

My theory is that *something* is causing the stream to be partially read before the file is saved by Django, then Django is reading from that point forward when saving to cloudstorage. If this is the case, it may be fixable by adding `file.seek(0)` after reading.

**Comment by olasitarska** [comment]
@LilithWittmann Pretty sure @Kazade theory is correct, I've used Cloudstorage backend on a couple of projects this way by using ImageField, and it worked alright!

**Comment by LilithWittmann** [comment]
@olasitarska @Kazade Yes we are validating images by checking their headers. I will try it, thanks!

@olasitarska we have to use the FileField instead of the ImageField because django dropped it's PIL support in 1.8 and appengine still don't support pillow. (and this is the reason why we are validating images manually)

**Comment by LilithWittmann** [comment]
Ok now the upload works but when I try to embed an image with ```image.url``` I get an encoded url like "https%3A//storage.googleapis.com/xxxx/uploads/2016/06/06/aufkleber_-_mit_footer.png". Do you have any idea why this happens?

**Comment by davidwtbuxton** [comment]
Hi @LilithWittmann is this with Djangae 0.9.2? Please update to a more recent version, this bug may have been fixed.

Specifically, there was a fix for incorrectly encoded names in #553 . Current version looks like https://github.com/potatolondon/djangae/blob/master/djangae/storage.py#L296

**Comment by ethagnawl** [comment]
For anyone who finds this issue after searching for something like, "how to use djangae.storage.serve_file" (I'm referencing @LilithWittmann's comment/request), I'd suggest having a look at [the virtual-art-sessions repository](https://github.com/dataarts/virtual-art-sessions/blob/69f990f4d6112d660bf1fc48bf57889e74898b5e/udon/views.py).
