### ISSUE TITLE
Djangae's `./manage.py runserver` starts a process that binds to 0.0.0.0

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#671]
A few seconds after doing `./manage.py runserver`, my Mac shows a dialog reading:

> Do you want the application “python” to accept incoming network connections?

This suggests that some process is attempting to bind to 0.0.0.0. This is bad from a security standpoint, as well as being annoying.

This dialog does not appear when running the same Django application using dev_appserver.py, which suggests this is caused by something Djangae is doing different.

This dialog only appears when using SDK version 1.9.32 or later. The same project, using the same version of Djangae, but with SDK 1.9.31, does not have this behaviour.

Tested using current master version of Djangae.

**Comment by WillsB3** [comment]
I believe that OSX requires root privileges to enable an application to listen to certain ports (although I'm not 100% sure).

What happens if you ask Djangae to listen on 3000 instead of the default 8000?

**Comment by moggers87** [comment]
@WillsB3 are you not thinking of _well-known ports_? I.e. ports 0 to 1023 always require root privileges on Unix-like systems. Also, that wouldn't explain why it works fine with old versions of the SDK (despite running on the same port).

@davidwtbuxton have you confirmed that 1.9.32 is actually binding to 0.0.0.0 and 1.9.31 isn't? `lsof` is your friend ☺

**Comment by davidwtbuxton** [comment]
Trying to make a test case for this, but now I get the same behaviour with `dev_appserver.py` as `./manage.py runserver`.

Again, switching to the 1.9.31 or earlier SDK does not show a dialog to accept incoming connections.

So that suggests it is nothing to do with Djangae, but then how come I didn't get the dialog when using dev_appserver.py with the other project?

Needs more investigating.

**Comment by davidwtbuxton** [comment]
@robcharlwood what do you see? Test project https://github.com/davidwtbuxton/djangae-bind-test

**Comment by robcharlwood** [comment]
@davidwtbuxton I will take a look over lunchtime today and let you know. :)

**Comment by adamalton** [comment]
I can confirm that:

1. This issue definitely happens with the 1.9.32 SDK but does not happen with the 1.9.31 SDK.
2. The issue definitely happens without djangae - just running `dev_appserver.py` from the 1.9.32 SDK on a directory which contains the default skeleton GAE project (app.yaml and main.py) causes the issue.  Running the 1.9.31 `dev_appserver.py` on the same project does not trigger the issue.
3. Ergo, it's nothing to do with Djangae.
4. The `dev_appserver.py` files in those 2 SDKs are identical, so it's something further down the chain.
5. I've tried looking further down the chain (albeit not very hard) and can't see what is causing it.

**Comment by davidwtbuxton** [comment]
What's really weird is that dev_appserver.py doesn't _always_ trigger this issue. I accept that it isn't a Djangae problem.

**Comment by adamalton** [comment]
The firewall dialogue is triggered when we reach this line (825) in `google/appengine/tools/devappserver2/devappserver2.py`:

```python
self._dispatcher.start(options.api_host, apis.port, request_data)
```

I've tried digging down from there, but just got lost in a world of crazy.

**Comment by adamalton** [comment]
It consistently triggers it for me.

**Comment by WillsB3** [comment]
Looks like this might have [happened before](http://stackoverflow.com/questions/17371089/prevent-osx-firewall-from-popping-up-when-developing-appengine-go-application). 

Unfortunately the user doesn't provide any details on the conversation he had with GAE team.

**Comment by davidwtbuxton** [comment]
Closing, learned helplessness.
