### ISSUE TITLE
Move the simulated contenttypes into djangae.contrib.contenttypes

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#682]
In djangae/apps.py we patch contenttypes to use "simulated contenttypes" which are an in-memory approximation of the normal content type behaviour. This is necessary for a couple of reasons:

1. `django.contrib.contenttypes` uses bulk_create, which with the appengine backend is limited to 25 entities - this causes migrate to explode
2. `django.contrib.contenttypes` suffers from eventual consistency issues on the datastore

We have to monkey-patch things because the `ContentType` model is not swappable, however, we need to patch things after contenttypes has loaded, which means djangae would need to come after `django.contrib.contenttypes` in `INSTALLED_APPS` which isn't ideal.

Instead it will be far cleaner to add `djangae.contrib.contenttypes` which must be in `INSTALLED_APPS` after `django.contrib.contenttypes`. The mere inclusion of this app will do the patching removing the need for the `DJANGAE_SIMULATE_CONTENTTYPES` setting.

Going forward it might be worth seeing if we can send a patch upstream to allow making the ContentType model swappable so we can provide a much cleaner solution to this.

**Comment by olasitarska** [comment]
This is also required for Django 1.10 support, as something changed in the order in which apps are registered -- this hasn't been an issue before 1.10.

**Comment by timgraham** [comment]
The main reason that Django is hesitant to add more swappable models and make swappable models a public API is that they can create real headaches with migrations.

I certainly would like to help you avoid hacks though.

**Comment by Kazade** [comment]
OK, I'll see if I can find some time to give this some thought and come up with some kind of proposal. Thanks!
