### ISSUE TITLE
Support retries option in db.transaction.AtomicDecorator

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#714]

**Comment by Kazade** [comment]
Obviously this will only work when used as a decorator as opposed to a context manager, so if someone tries that we should throw a "What *are* you doing?" error :p

**Comment by adamalton** [comment]
Are we talking about the retries option which can be passed down to App
Engine, or having a separate loop of our own which does:

tries = 0
while tries < retries:
    try:
        return transaction()
    except TransactionFailedError:
        tries += 1

Obvious that kind of loop could only be done if AtomicDecorator is used as
a decorator, not as a context manager.  But surely we could pass down the
App Engine option without changing anything?

**Comment by Kazade** [comment]
App Engine doesn't have a magical retry setting, they handle it in their RunInTransaction thing:

```
    for _ in range(0, retries + 1):
      _SetConnection(conn.new_transaction(options))
      ok, result = _DoOneTry(function, args, kwargs)
      if ok:
        return result
```

**Comment by adamalton** [comment]
Oh I see.  I was looking at the SDK code thinking _"there's already a 'retries' option here"_, but of course that option only exists for their decorator.

I think the first thing we should do is put a `do_with_retries` decorator into djangae/<something>/utils.py, as that would be useful anyway.  And then at least people can do:

```python
@do_with_retries(attempts=3, catch=TransactionFailedError)
@transaction.atomic()
def my_function():
    do_stuff_with_the_datastore()
```

If people then really want the retry stuff combined into the `atomic` decorator then we can add that in as a further enhancement.

**Comment by Kazade** [comment]
You mean... like this one? https://github.com/potatolondon/djangae/blob/master/djangae/utils.py#L95

**Comment by adamalton** [comment]
Yes, but less weird.

**Comment by adamalton** [comment]
By which I mean:

* The usage should be `@retry(**retry_params)(function, function_args, function_kwargs)`, not the current `@retry(function, function_args, mixed_function_and_retry_kwargs`).
* Which exceptions it catches should be one of the retry params.
* It should probably have configurable backoff (and maybe timeout) options.
* Inline imports?

**Comment by adamalton** [comment]
And documentation 😀

**Comment by Kazade** [comment]
Right, yes good idea - you should *definitely* send a PR for that ;)
