### ISSUE TITLE
Error with Docker

### ISSUE THREAD

**Issue by avara1986** [potatolondon/djangae#715]
Running Djangae inside a Docker container, I get an error:
```
Traceback (most recent call last):
  File "/app/sitepackages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/app/sitepackages/csp/middleware.py", line 43, in process_response
    replace=replace)
  File "/app/sitepackages/csp/utils.py", line 58, in build_policy
    policy.append('report-uri %s' % ' '.join(report_uri))
TypeError: sequence item 0: expected string, __proxy__ found
```
And `report_uri` is `django.utils.functional.__proxy__`

**Comment by moggers87** [comment]
This is a Django-CSP issue. The latest version allows only strings in the `CSP_REPORT_URI` setting. Either change that setting to a string literal or install an earlier version of Django-CSP.

**Comment by adamalton** [comment]
Oh, that's due to a change in Django CSP.

The current solution is to pin that to `django-csp==2.0.3`.

Adam
