### ISSUE TITLE
Change indexing behaviour for `__contains` on CharField

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#730]
Currently, when you do an `__contains` filter on a `CharField`, Djangae's special indexing adds one or several index columns to store all the possible substrings.

There are 2 things wrong with this:
1. If there are more than 500 different substrings then it uses multiple columns to store them.  This is based on the incorrect idea that list fields can contain a maximum of 500 items.  It turns out that that's not true: #729.
2. The `number_of_permutations` method (which calculates the number of substrings) doesn't take account of duplicates.  E.g. for the string `"aba"` it assumes that there are 6 substrings (`["a", "ab", "aba", "ba", "b", "a"]`), but actually there are only 5 distinct substrings.

The maximum amount of text that we can index is limited by:
1. The `google.appengine.api.datastore._MAX_INDEXED_PROPERTIES` (see #729).
2. The fact that an entity can be a maximum of 1MB.
3. The fact that the maximum indexable single string value is 1500 bytes (`google.appengine.api.datastore_types._MAX_STRING_LENGTH`).

We should be able to scrap both the `MAX_COLUMNS_PER_SPECIAL_INDEX` setting and our `CHARACTERS_PER_COLUMN` variable.

**Comment by martinallison** [comment]
Another thing to watch out for here is the exploding indexes problem. Way back before the search API, I implemented FTS exactly like Djangae does `__contains` and `__startswith`, but after a while the indexes started to scream and not build.

We should probably add some documentation/warning about this since it's a 'problem' with the current implementation as well.

**Comment by Kazade** [comment]
Right, here's a rethink of all of this now that I'm aware of various issues with the current implementation.

1. Storing all permutations of strings is wasteful, specifically you can reduce the permutations to N for an N length string by storing `str`, `str[1:]`, `str[2:]` etc. and using a `startswith` style query, but this uses up an inequality
2. Storing permutations on the entity itself causes *insane* performance issues - those `idx_` fields get very heavy and the transfer over the RPC massively increases query time on *all* queries, not just ones filtered by the index field. You *could* use projections to avoid loading those fields, but alas, if you filter on something it must be returned in the projection.

The only way we can really avoid performance and scalability issues is to:

1. Store contains/icontains indexes in a separate kind
2. Only store `endswith` permutations
3. Queries on icontains would require an additional `startswith` keys_only lookup and convert to a `pk__in` in the master query
4. We maybe can leverage ancestors to make this work without using up entity groups
