### ISSUE TITLE
Cloud Storage Hashing URL

### ISSUE THREAD

**Issue by erdem** [potatolondon/djangae#745]
Is there hashed URL support on the Djangae cloud storage backend?  

I was looking built-in hashing method for public images but I didn't see on the codebase. I think, It could be great if the project has built-in hashing support.

like:
`https://storage.googleapis.com/bucket-name/test.jpg` ---> `https://storage.googleapis.com/bucket-name/LOiWmf4asOJSM.test.jpg`

**Comment by davidwtbuxton** [comment]
Hi,

Do you want a hashed object name to have a public image which isn't guessable? If so, there's the [Images API which gives you `get_serving_url()`][1] which is great for that use case.

Or were you thinking of something different?

David B.

[1]: https://cloud.google.com/appengine/docs/python/images/

**Comment by erdem** [comment]
Hi @davidwtbuxton 

Sorry for the delayed answer, you are right `get_serving_url` fixed the issue. 

I think, it will be great if you add a secure URL option to storage backend. 

Here is my custom cloud storage backend implementation:


`

    from djangae.storage import CloudStorage as DjangaeCloudStorage


    class CloudStorage(DjangaeCloudStorage):

        def url(self, filename):
            safe_name = urllib.quote(filename.encode('utf-8'))
            quoted_filename = '/{0}/{1}'.format(self.bucket, safe_name)
            cs_file_obj_path = "/gs{}".format(quoted_filename)
            blob_key = blobstore.create_gs_key(cs_file_obj_path)
            serve_url = get_serving_url(blob_key, secure_url=True)
            return serve_url

`

Thanks
