### ISSUE TITLE
Django 1.10.1 + Djangae + Cloud SQL 2nd generation bug

### ISSUE THREAD

**Issue by briva** [potatolondon/djangae#757]
Hi guys, i'm currently setting up my project, its running well at start but after 10s request on my api the server return me 500 errors sporadically and all the time after few other requests.

**OperationalError: (2062, 'Cloud SQL socket open failed with error: No such file or directory')**

See the trace :

>   File "/base/data/home/apps/e~project-x23-staging-core/1.395474513923813504/lib/django/db/utils.py", line 94, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/base/data/home/apps/e~project-x23-staging-core/1.395474513923813504/lib/django/db/backends/base/base.py", line 199, in ensure_connection
>     self.connect()
>   File "/base/data/home/apps/e~project-x23-staging-core/1.395474513923813504/lib/django/db/backends/base/base.py", line 171, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/base/data/home/apps/e~project-x23-staging-core/1.395474513923813504/lib/django/db/backends/mysql/base.py", line 265, in get_new_connection
>     conn = Database.connect(**conn_params)
>   File "lib/MySQLdb/__init__.py", line 81, in Connect
>     return Connection(*args, **kwargs)
>   File "lib/MySQLdb/connections.py", line 193, in __init__
>     super(Connection, self).__init__(*args, **kwargs2)
> OperationalError: (2062, 'Cloud SQL socket open failed with error: No such file or directory')

Anyone have an idea to solve this ?

**Comment by nealedj** [comment]
It sounds like you're hitting the open connection limit for Cloud SQL which implies that your connections aren't being closed at the end of your requests.

Assuming you have `settings.CONN_MAX_AGE == 0` then Django should close them for you.

I think Django's method of closing connections doesn't work for requests run on the task queue so if you have tasks running you may need to call `django.db.close_connection` at the end of the request.

**Comment by briva** [comment]
Another stacktrace problem raise with rest_framework :

> OperationalError: (2062, 'Cloud SQL socket open failed with error: No such file or directory')
> at __init__ (lib/MySQLdb/connections.py:193)
> at Connect (lib/MySQLdb/__init__.py:81)
> at get_new_connection (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/backends/mysql/base.py:265)
> at connect (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/backends/base/base.py:171)
> at ensure_connection (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/backends/base/base.py:199)
> at __exit__ (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/utils.py:94)
> at ensure_connection (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/backends/base/base.py:199)
> at _cursor (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/backends/base/base.py:204)
> at cursor (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/backends/base/base.py:233)
> at temporary_connection (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/backends/base/base.py:564)
> at __enter__ (/base/data/home/runtimes/python27/python27_dist/lib/python2.7/contextlib.py:17)
> at mysql_version (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/backends/mysql/base.py:369)
> at __get__ (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/utils/functional.py:35)
> at supports_microsecond_precision (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/backends/mysql/features.py:54)
> at __get__ (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/utils/functional.py:35)
> at data_types (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/backends/mysql/base.py:185)
> at __get__ (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/utils/functional.py:35)
> at db_type (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/fields/__init__.py:629)
> at process_lhs (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/lookups.py:148)
> at as_sql (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/lookups.py:155)
> at compile (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/sql/compiler.py:353)
> at as_sql (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/sql/where.py:79)
> at compile (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/sql/compiler.py:353)
> at as_sql (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/sql/compiler.py:376)
> at execute_sql (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/sql/compiler.py:824)
> at __iter__ (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/query.py:54)
> at _fetch_all (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/query.py:1087)
> at __len__ (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/query.py:238)
> at get (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/db/models/query.py:379)
> at authenticate_credentials (lib/rest_framework/authentication.py:193)
> at authenticate (lib/rest_framework/authentication.py:188)
> at _authenticate (lib/rest_framework/request.py:318)
> at user (lib/rest_framework/request.py:195)
> at __getattribute__ (lib/rest_framework/request.py:355)
> at perform_authentication (lib/rest_framework/views.py:310)
> at initial (lib/rest_framework/views.py:384)
> at dispatch (lib/rest_framework/views.py:462)
> at handle_exception (lib/rest_framework/views.py:434)
> at dispatch (lib/rest_framework/views.py:474)
> at view (lib/rest_framework/viewsets.py:87)
> at wrapped_view (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/views/decorators/csrf.py:58)
> at _get_response (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/core/handlers/base.py:185)
> at _get_response (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/core/handlers/base.py:187)
> at _legacy_get_response (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/core/handlers/base.py:249)
> at inner (/base/data/home/apps/e~project-x23-staging-core/1.395475632427710359/lib/django/core/handlers/exception.py:39)

**Comment by adamalton** [comment]
On 7 September 2016 at 15:55, David Neale <notifications@github.com> wrote:

> I think Django's method of closing connections doesn't work for requests
> run on the task queue so if you have tasks running you may need to call
> django.db.close_connection at the end of the request.
>

I'm pretty sure Djangae ensures that the environment is the same for
requests called by the task queue, so it should work the same on tasks and
"normal" requests, AFAIK.

My guess is that it's not managing to connect to SQL at all, maybe due to
the App Engine app not being whitelisted in the Cloud SQL settings, or the
instance name/other DB setting not being right, or something like that...?

**Comment by briva** [comment]
@adamalton nope because the first calls works well and after 20-30 request . I get 500 and this message :/

**Comment by briva** [comment]
I just test with the first version of Cloud sql : same issue :/

**Comment by adamalton** [comment]
Ah right, sorry, I should have read your original message properly!

Did you copy your project setup from djangae-scaffold
<https://github.com/potatolondon/djangae-scaffold>?

Do you have any `script` handlers in app.yaml which do not use the wsgi.py
file that's given in djangae scaffold?

**Comment by briva** [comment]
Finally i found the bug :

in my appengine_config.py, i commented that :

> 
> def webapp_add_wsgi_middleware(app):
>     from google.appengine.ext.appstats import recording
>     app = recording.appstats_wsgi_middleware(app)
>     return app

No bottleneck now :)
