### ISSUE TITLE
Inability to prefetch RelatedSetField causes many Datastore calls

### ISSUE THREAD

**Issue by mvd7793** [potatolondon/djangae#774]
Hello! I'm running into a problem in our deployment of Djangae due to `RelatedSetField`. With some sample models:

``` python
# =======   Models  ======= 
class Post(models.Model):
    content = models.TextField()
    tags = fields.RelatedSetField('Tag', related_name='posts')

class Tag(models.Model):
    name = fields.CharField()
    # Backref to posts

# =======   Usage  ======= 
# Serialize all Post models to JSON

posts = Post.objects.all()
serialized_posts = []

for post in posts:
    serialized_posts.append({
        "content": post.content,
        "tags": [{"name": tag.name} for tag in post.tags] # Repeated post.tags = bad
    })
```

In this example, `post.tags` is called once for each Post, which leads to a single Datastore call once per Post. Eventually, the number of datastore calls becomes overwhelming, whereas `Post.objects.all()` and `Tag.objects.all()` both run relatively quickly. 

I _think_ the answer to this would generally be prefetching, but I could be wrong. Is there a better way to go about this? (Is there a good way to batch this up that I'm missing?)

**Comment by Kazade** [comment]
Hi!

Given the code above, I wouldn't expect the tags to be pre-fetched unless you called `Post.objects.prefetch_related().all()` when creating your `posts` queryset. 

But, even if you do I'm not convinced it will actually fetch them then `posts` is iterated. Could you give it a try and see if it does?

If not, then we should look into fixing that. For now though you could do something like this:

```
posts = Post.objects.all()
tags = {}
# Build a dictionary of Post -> Tags 
[ tags.setdefault(tag.post_id, []).append(tag) for tag in Tag.objects.all() ]
for post in post:
  post_tags = tags[post.pk]
  # etc.
```

But that's obviously not ideal!

**Comment by mvd7793** [comment]
Hi! Thanks for the quick reply:

You're right -- I didn't demo attempting to prefetch in my code. The code to do that errors, specifically:
```python
Post.objects.all().prefetch_related('tags')
```
gives the error `'tags' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().`

I think this occurs because `RelatedIteratorManagerBase` is missing a `get_prefetch_queryset()` method. I took a stab at writing one yesterday, but I wasn't able to get something working in the few hours I put into it. 

I believe it would be very similar to [this method](https://github.com/django/django/blob/3c447b108ac70757001171f7a4791f493880bf5b/django/db/models/fields/related_descriptors.py#L880) in Django's `ManyRelatedManager` under the `ManyToManyDescriptor`. Specifically, I think the todo is to implement a `get_prefetch_queryset()` that Django can use.

**Comment by Kazade** [comment]
OK, so I've spent some time looking at this and Django apparently doesn't make it easy!

The easy part is generating the actual queryset to get all the related objects, the problem then becomes convincing Django to store those returned objects on the right instances (e.g. store the right Tags on the right Posts).

`get_prefetch_queryset` requires you return two functions. The first returns a dictionary key to be generated by the passed related instance (e.g. Tag) and the second returns the matching dictionary key given the source instance (e.g. Post). The reason this falls apart is that Tags belong to more than one Post but I can't see how you can make Django work with that.

I still don't understand how M2M field does it, going to keep digging!

**Comment by Kazade** [comment]
@mvd7793 there's a fix in the above PR, thanks for bringing this to our attention. Sorry I couldn't get time to fix it earlier!

**Comment by mvd7793** [comment]
Thanks for taking the time to fix. :)
