### ISSUE TITLE
where to disable db constraints

### ISSUE THREAD

**Issue by cyrfer** [potatolondon/djangae#778]
The [djangae documentation](https://djangae.readthedocs.io/en/latest/db_backend/#unique-constraint-checking) talks about disabling constraint checks with `settings.DJANGAE_DISABLE_CONSTRAINT_CHECKS`. 

My problem is I do not know where to put that "code". The "settings" module seems like a clue, but I don't know which file would be smart to add the code to, and I'm not sure if I need to assign a value like `True` to it or what I do with the variable.

**Comment by davidwtbuxton** [comment]
Indeed, your project's settings module is where it should go, and it should have a value of `True` or `False`.

Questions about using Djangae are more appropriate for [the Djangae users' forum][1]. This GitHub issues tracker is intended for discussion of bugs in Djangae itself.

[1]: https://groups.google.com/forum/#!forum/djangae-users
