### ISSUE TITLE
Entities are still added to cache with DJANGAE_CACHE_ENABLED = False

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#783]
In djangae/db/backends/appengine/caching.py, we check for the `DJANGAE_CACHE_ENABLED` setting, and if it's `False` then we don't bother looking in the cache for entities.

But the `add_entities_to_cache` function doesn't do that check, and this function is called directly from various places in compiler.py, so it looks like we still put entities into the cache even when it's disabled.

**Comment by nealedj** [comment]
Fixing this should also fix some issues with the remote sandbox.

`add_entities_to_cache` appears to try to remove entities with `_remove_entities_from_memcache_by_key` if saving in a transaction. This gets the entities before deleting them and can cause a `UnpicklingError: NEWOBJ class argument isn't a type object` error.

Finally, `remove_entities_from_cache_by_key` is called by the `DeleteCommand`. This also ends up calling `_remove_entities_from_memcache_by_key`.

Two functions to short-circuit here if `DJANGAE_CACHE_ENABLED == False`:

- `add_entities_to_cache`
- `remove_entities_from_cache_by_key`

**Comment by adamalton** [comment]
For the benefit of anyone who stumbles across this after googling for `UnpicklingError: NEWOBJ class argument isn't a type object`: that error only happens when using the remote shell and is due to this bug in App Engine: https://code.google.com/p/googleappengine/issues/detail?id=7876.  But allowing us to avoid it would be very useful!
