### ISSUE TITLE
query filter with __iexact is not working

### ISSUE THREAD

**Issue by Ali-aqrabawi** [potatolondon/djangae#784]
when i use __iexact with query filter it does not work : 

persons = Person.objects.filter(Q(name__iexact=q))

no errors no exceptions , but it does not return anything

**Comment by adamalton** [comment]
What happens if you do it without wrapping it with `Q`?

**Comment by Kazade** [comment]
Also, did you remember to resave all your `Person` objects once the index was added to `djangaeidx.yaml`?  The special indexing needs to generate hidden columns which only happens on save. Until then, nothing will match the filter.

**Comment by Ali-aqrabawi** [comment]
i tried without Q but same issue , 

> did you remember to resave all your Person objects once the index was added to djangaeidx.yaml? 

i'm not sure about this , but do you mean that the query will not work for the already existed objects before djangaeidx.yaml was generated ? 

so i will re add __iexact to the query and store a new object and then try the query again .

**Comment by adamalton** [comment]
> do you mean that the query will not work for the already existed objects before djangaeidx.yaml was generated ?

Yes, correct.

> so i will re add __iexact to the query and store a new object and then try the query again 

If the index is listed in djangaeidx.yaml then newly-created objects should be returned by the query.

**Comment by Kazade** [comment]
I'm going to assume that resaving the objects fixed the problem. Reopen if you're still having trouble! :)
