### ISSUE TITLE
Simulated ContentTypes & Django admin LogEntry

### ISSUE THREAD

**Issue by philoozushi** [potatolondon/djangae#791]
Using current Djangae scaffold, and Djangae v0.9.7+ :
In Django admin "Recent Actions" box, all logs display "Unknown content" for the content-type.

I don't get how exactly the simulated ContentTypes work, but in Django shell, I can see a correct `content_type_id` for LogEntries, matching an existing `ContentType`, however the ForeignKey `content_type` field raises an error.

```
>>> entry = LogEntry.objects.last()
>>> entry.content_type_id
-5352591944405510358L
>>> ContentType.objects.get(id=-5352591944405510358L)
<ContentType: MyModel>
>>> entry.content_type
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "...sitepackages/django/db/models/fields/related_descriptors.py", line 169, in __get__
    rel_obj = qs.get()
  File "...sitepackages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: ContentType matching query does not exist.
```

**Comment by adamalton** [comment]
This is the bit that looks suspicious:

```pythong
>>> entry.content_type_id
-5352591944405510358L
```

I think this is probably the same underlying issue as this: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/djangae-users/HHiJCqGxeAc/aOP6qDXdAwAJ

It seems that we're getting negative content type IDs, which is clearly wrong.  The obvious culprit is this line: https://github.com/potatolondon/djangae/blob/427a4f34a9a58b9a7dabd899fe1c5564c0969f6b/djangae/contrib/contenttypes/models.py#L38

**Comment by adamalton** [comment]
If you could write a test that produces the issue then that would be incredibly useful in helping to get it fixed.

**Comment by philoozushi** [comment]
Sure, I though it was suspicious too.
I added a test to check if ContentType ids are positive.
