### ISSUE TITLE
Make special indexes support negation

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#80]
Here's an example... at the moment if you use the following query:

    Article.objects.filter(headline__startswith="bananas")

The indexer will add a list property, with ['b', 'ba', 'ban' ...] and then convert the query to an exact query. However, if you do this:

    Article.objects.exclude(headline__startswith="bananas")

It won't work. This query requires that we explode the query into:

    Article.objects.filter(Q(headline__lt="bananas") | Q(headline__gt="bananas" + u'\ufffd'))

We need to improve the indexing to deal with an indexer flag, and potentially changing the filter completely in that case.

We should also make exclude(headline__istartswith) add an iexact column for it etc.

**Comment by olasitarska** [comment]
This is fixed already.
