### ISSUE TITLE
What license is Djangae released under?

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#801]
The [LICENSE.md in the repository][license] is a [3-clause BSD license][bsd], but the [setup.py says Djangae is using an MIT license][setup].

Assuming one of these is correct, which is it?

[license]: https://github.com/potatolondon/djangae/blob/151a4dda5ea213ad5e32a6e5499d944365788a03/LICENSE.md
[bsd]: https://opensource.org/licenses/BSD-3-Clause
[setup]: https://github.com/potatolondon/djangae/blob/67d1a088f77cde6173b066093ec6a2e00e510496/setup.py

**Comment by Kazade** [comment]
Fixed in #802
