### ISSUE TITLE
`is_authenticated` can't be a method in Django >=1.10

### ISSUE THREAD

**Issue by BogdanL** [potatolondon/djangae#825]
Since 1.10, Django doesn't allow `User.is_authenticated` to be a method but only an attribute or a property 

from `django/docs/ref/checks.txt`:
`<User model>.is_authenticated must be an attribute or property rather than a method. Ignoring this is a security issue as anonymous users will be treated as authenticated!`

Djangae is still making `user.is_authenticated()` calls in `djangae/contrib/gauth/middleware.py` and `djangae/contrib/gauth/tests.py`.

I am not sure how this is normally handled, given that Djangae also supports 1.8 and 1.9 – maybe something like this? 

```
if DJANGO_VERSION < (1, 10, 0):
    return user.is_authenticated()
 else:
    return user.is_authenticated
```

**Comment by adamalton** [comment]
Was this actually causing an error?  According to [the release notes](https://docs.djangoproject.com/en/1.10/releases/1.10/#using-user-is-authenticated-and-user-is-anonymous-as-methods) `is_authenticated` and `is_anonymous` will still work as methods up to Django 2.0.

**Comment by asendecka** [comment]
@adamalton I don't think there was any error, there is only a remark in the issue that Django docs are stating that `is_authenticated` method is deprecated and will be removed in next versions. 

It's better to be prepared in advance for the change.

**Comment by adamalton** [comment]
Fair enough, in which case we should do the same thing for our uses of `is_anonymous` (of which there are a few).

I was also thinking (if we're going to tweak it anyway), that we can just do

```python
if callable(user.is_X):
    return user.is_X():
return user.is_X
```

rather than importing the Django version.
