### ISSUE TITLE
Improve djangae.utils.retry

### ISSUE THREAD

**Issue by grzes** [potatolondon/djangae#828]
Retry is essential in proofing against transactionfailed errors. We tried to provide a retry tool, but it has a few shortcomings:

- It has the builtin backoff, it should be optional instead, there should be a way to do immediate retries without any unnecessary sleeps. Appengine's builtin transactional() decorator retries transactions immediately.

- It would be helpful to have it as a context manager, currently retrying a block of code requires it to be wrapped up in a function.

- It catches a broad selection of appengine errors, we should make this optional, or allow via a param to only catch transactionfailederrors

**Comment by adamalton** [comment]
Some similar notes about this here: https://github.com/potatolondon/djangae/issues/714#issuecomment-249143768

**Comment by grzes** [comment]
exactly like that!
