### ISSUE TITLE
Memcache layer slows down large serialization significantly

### ISSUE THREAD

**Issue by mvd7793** [potatolondon/djangae#831]
For sample models such as the following, with ~100 of each model, let's say we run the query shown, knowing we intend to serialize all data.

```python
# =======  Models  ======= 
class Post(models.Model):
    content = models.TextField()
    authors = fields.RelatedSetField('Author', related_name='posts')

class Author(models.Model):
    name = fields.CharField()
    awards = fields.RelatedSetField('Awards')
    
class Awards(models.Model):
    name = fields.CharField()

# =======  Query  ======= 
posts = Post.objects.all().prefetch_related('authors').prefetch_related('authors__awards')
# ...
# Perform a cheap operation that causes the Posts iterator to run.
# ...
serialize(posts)
```

Note that to run this code, you need the fix in #830. Given some significant number of models, we would expect most time to occur in fetching if the rest of the data on the models is simply in-memory:

```
Posts fetch (expensive)
|
|---> Author fetch (expensive)
      |
      |---> Tags fetch (expensive)
       		|
       		|---> Serialization (cheap)
```

What I've found in testing is that serialization is rather expensive because of memcache calls. I happen to be doing nested serialization with [Django Rest Framework](http://www.django-rest-framework.org/), which will traverse these links for you, but since nested objects are prefetched it should be cheap. Instead, I've found serialization takes 4000ms. A deep dive showed hundreds of `memcache.set` RPCs, which I traced to `KeyPrefixedClient.set_multi_async`. There are a couple problems here. 

1. `KeyPrefixedClient.set_multi_async` doesn't respect the `DisableCache` decorator, so it's impossible to disable these synchronous `set` calls.
2. The `set` calls are all done synchronously even though they're not required, and there isn't a way to batch them.

Fixing the first problem brings serialization down to 2000ms, which still isn't great, but debugging that is a separate issue.

**Comment by adamalton** [comment]
Thanks Matthew.

A bit of thinking out loud from me:

* `KeyPrefixedClient.set_multi_async` only becomes synchronous when `self.sync_mode` is `True`, which as far as I can tell is only ever the case in tests.
    - So my analysis says that your _2._ is not correct.  Do you agree @mvd7793?
* `KeyPrefixedClient.set_multi_async` is only called by `_add_entity_to_memcache`, which is only called by `add_entities_to_cache`, which respects the `CACHE_ENABLED` flag, but does not look at the flag set by the `DisableCache` decorator (`get_context().memcache_enabled`).
    - `add_entities_to_cache` is called from several places, some of which check `get_context().memcache_enabled` before calling it and some of which don't.
        * Ones which _do_ check: `get_from_cache_by_key` and `get_from_cache`.
        * Ones which do _not_ check: all of the ones in `djangae/db/backends/appengine/commands.py`.
    - To fix this it looks like we would need to check `get_context().memcache_enabled` inside `add_entities_to_cache`.

**Comment by Kazade** [comment]
Thanks for this @mvd7793 - I don't think anyone has done any serious performance profiling when fetching large querysets - it's something I've been meaning to do.

I think we probably need to reconsider when we cache things depending on the size of the resultset. The caching layer is awesome when you are working with a handful of entities - but any gains will be rapidly wiped out when retrieving a large number of results. 

I'm open to suggestions on how we should determine whether to cache or not. Perhaps a configurable threshold (e.g. < 30 results)? Anyone know the max number of cache keys you can set in a single RPC call?

I fear there are also issues with the local context cache when fetching a large number of results by key too.

**Comment by mvd7793** [comment]
@adamalton: I should modify my previous statement: I suspect the memcache sets happen serially because the DRF serialization access pattern is one at a time. This maps to a nasty RPC timeline that looks like this: http://imgur.com/a/D6xp3. I'm not sure how the caching layer would cache multiple objects at once, though perhaps these RPCs come from one-by-one accesses of nested objects (`Author` and `Awards` in my example).

@Kazade: For sure! Google's [Stackdriver Trace](https://cloud.google.com/trace/) will display both Datastore and Memcache RPCs, and can optionally also display your log lines on the same timeline. It has been exceedingly helpful for debugging.

As a minimal fix, I would suggest that `disable_cache` should also affect memcache set RPCs, as specified by @adamalton. 

Thinking about a longer-term fix, as you said, caching every element one-by-one for large sets isn't great. There [isn't a numerical limit](https://cloud.google.com/appengine/docs/python/memcache/#limits) on memcache `multi` calls... just size limits. 

If you could cache all fetched objects in a single async RPC, that seems more optimal. I would still advocate for the `disable_cache` fix so a user could choose to write the fastest endpoint possible, or perhaps this should be opt-in behavior instead.

**Comment by Kazade** [comment]
Right I've discovered the problem. If you do a query by multiple keys (e.g. a pk__in=[]) this will perform a `datastore.Get()` which is memcachable. At this point we correctly call `add_entities_to_cache` to cache all the results, but then this happens: 

https://github.com/potatolondon/djangae/blob/master/djangae/db/backends/appengine/caching.py#L255

i.e. it makes a `memcache.Set` call per entity (but it does save multiple keys if there are unique fields on the model). I think the solution is to set some configurable batch size and then change that loop to cache entities in batches to reduce RPC calls (a batch size is cleaner than trying to work out if we hit a memory size limit).

**Comment by Kazade** [comment]
OK, more thinking.. 

The batch size should be 32, and should be batches of keys rather than entities. This is because the max size of an entity is 1MB and the max memcache set_multi is 32MB.

**Comment by Kazade** [comment]
Right, ignore all of that, it turns out _add_entity_to_memcache is terribly named, and actually does add all the entities at once. 

I can't figure out why there are some many memcache.Set calls in your trace.. it does appear that when we do a Get we do a set_multi..
