### ISSUE TITLE
Django 1.9 / AttributeError: 'Settings' object has no attribute 'MIDDLEWARE'

### ISSUE THREAD

**Issue by philoozushi** [potatolondon/djangae#861]
Just checked out and got this error :
```
AttributeError: 'Settings' object has no attribute 'MIDDLEWARE'
```
I'm using Django 1.9 and `MIDDLEWARE_CLASSES`.
Caused by this commit : 0458db2ca8a41b490af7346ae09dc41c3b056657 @davidwtbuxton, you can check my comment.

**Comment by davidwtbuxton** [comment]
Hi,

Could you paste the traceback please? At first glance, the use of `getattr` should guard against that specific error.

**Comment by davidwtbuxton** [comment]
Ignore me, I was thinking of `dict.get('foo')` when I wrote that. Sorry!

**Comment by philoozushi** [comment]
Thanks! :)
