### ISSUE TITLE
Zero is an invalid ID on App Engine

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#87]
Specifying it in a query should raise an error, at the moment we get the somewhat weird: google.appengine.api.datastore_errors.BadValueError: Incomplete key found for reference property  .

**Comment by Kazade** [comment]
Sorry for the late reply!

Yes you're on the right track. If we query for `pk=0`  or `pk__lte=0` we should raise EmptyResultSet. If we query on pk__gt=0 we should ignore the filter entirely. And if zero appears in a pk__in we should remove it from the list.

**Comment by davide-ceretti** [comment]
Great, thanks!

**Comment by LuRsT** [comment]
It seems that all these issues were solved, this ticket can now be closed.

I tested all the queries mentioned and each raises a DoesNotExist.

**Comment by olasitarska** [comment]
Thanks @LuRsT!
