### ISSUE TITLE
String-based PKs should not be limited to 500 characters

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#872]
Currently, in `djangae.db.utils.django_instance_to_entity` we have this:

```python
kwargs = {}
if primary_key:
    if isinstance(primary_key, (int, long)):
        kwargs["id"] = primary_key
    elif isinstance(primary_key, basestring):
        if len(primary_key) > 500:
            warnings.warn("Truncating primary key that is over 500 characters. "
                          "THIS IS AN ERROR IN YOUR PROGRAM.",
                          RuntimeWarning)
            primary_key = primary_key[:500]

        kwargs["name"] = primary_key
    else:
        raise ValueError("Invalid primary key value")
```

But (as we do with `djangae.fields.CharField`), I'm pretty sure we should be restricting the length to `from google.appengine.api.datastore_types import _MAX_STRING_LENGTH`, not to `500`.

**Comment by adamalton** [comment]
This actually causes an error if you try to do an insert with a string-based PK of more than 500 characters, because in `djangae.db.backends.appengine.commands.InsertCommand.execute` in the transaction that's inside the nested `insert_chunk` function, circa line 905, we do:

```python
if utils.key_exists(key):
```

which checks the *full* value of the PK.  And then when we try to insert, the code in `django_instance_to_entity` truncates the PK, and then does the insert, which means that we're now operating on more than 1 entity group, and so the transaction gives us:

```python
BadRequestError: cross-groups transaction need to be explicitly specified (xg=True)
```

It also means that the existence check is obsolete because it's not checking for the same value that we're inserting.

I actually think that if you try to insert a PK that's too long, then it should just blow up in your face.

**Comment by Kazade** [comment]
OK, so I believe the original reason that the truncation was there was due to a Django test blowing up when it tried to insert a really long key. But I guess we can just skip that test.

I agree we should remove the truncation, but actually I think the limit to key names *is* 500 chars and not 1500 bytes (hence the test blowing up)

**Comment by seawolf42** [comment]
Per my understanding, this is true, it is a 500 character limit. See [this summary](https://stackoverflow.com/a/33061526/1886109) from one of the Google engineers.
