### ISSUE TITLE
Implement our own MultiQuery

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#875]
This'll take some explaining.. so here goes...

MultiQuery is an entirely client side construct. Whenever you do an IN or OR query on the datastore it runs several queries over the RPC (all ordered in the same way) and merges the results. This is why MultiQuery doesn't feature in the Cloud Datastore API. The core operations on the datastore are Get, Put, Delete and Query only.

If we are to start supporting the Cloud Datastore API, we must replace MultiQuery with something, and if we have to replace MultiQuery on Cloud Datastore, we might as well use the replacement on the normal datastore too. 

As it happens we can actually improve things a bit. We can thread the fetching of multiple queries for example if threading is available (likely) and we can bump the limit of queries from 30, to something higher (e.g. 50, or 100). I'm fairly sure the 30 limit was just to prevent hammering the RPCs but given that things have drastically improved on the datastore since the switch to the high replication datastore (and the limit was never increased) it's probably safe to bump it a little. 

Originally I was going to include this in the Cloud Datastore support feature, but actually it makes sense to do it standalone. There is the beginnings of an implementation in this branch here: https://github.com/potatolondon/djangae/blob/cloud-datastore-support/djangae/db/backends/appengine/meta_queries.py#L12

**Comment by adamalton** [comment]
I support this motion!
