### ISSUE TITLE
New stub management has introduced a breaking change

### ISSUE THREAD

**Issue by farridav** [potatolondon/djangae#879]
[This PR](https://github.com/potatolondon/djangae/pull/864) introduced breaking changes for me, and I'm unable to build my project.

I have my project setup like in [django-scaffold](https://github.com/potatolondon/djangae-scaffold/), which requires the test stubs to be setup before the application is initialised (to get the secret config from datastore) [see here](https://github.com/potatolondon/djangae-scaffold/blob/master/project_name/settings.py#L24)), whereas this new testing approach sets up and tears down stubs before and after tests respectively using a nose plug-in (or the new djangae test runner)

My setup:
```
django-nose==1.4.4
nose==1.3.7
Django==1.10.6
Djangae==0.9.10-alpha
AppEngine SDK 1.9.50
```` 

I had to add the `noseplugin` manually using [NOSE_PLUGINS](https://django-nose.readthedocs.io/en/latest/usage.html#custom-plugins), you may want to document the use of this), and I also needed to initialise the stubs also on `begin` as Django runs migrate on the datastore DB well before a test is run (side note: is this because the db backend is not considered transactional?).

Can we get a bit more documentation added on how to run/manage a test suite, as this is largely affected by the management of the stubs in Djangae, and if you have any immediate advice that can help unblock me, that'd be awesome.

Here's my current work in progress Djangae fork https://github.com/potatolondon/djangae/compare/master...farridav:farridav/fix_test_runner, which is now failing on image uploads, but is somehow passing before the aforementioned pull request was merged in ([Stacktrace here](https://pastebin.com/DbRHWV98)).

- Is it possible to use Imagefields within tests, have you managed to do so? (I could previously)
    - If so, what backend should be used, CloudStorage/Blobstore 
- Can you get your test suite working with the current nose plugin (without implementing the `begin` hook, and adding `NOSE_PLUGINS` to django settings
- Is the secrets approach taken in the scaffold project, and the scaffold project no longer best practice? 
- Do you have any insight into why file uploads fail during test?

**Comment by Kazade** [comment]
Hi, 

Sorry things have broken for you. Just to clarify, I assume that you are using the "test" sandbox when running tests as recommended in the docs? If so, then you have two options to avoid the SECRET_KEY problem:

1. Use the local sandbox instead (although this will affect startup/shutdown time of test runs)
2. Use a different settings file for tests where the SECRET_KEY is hard coded

It is still recommended you store your secret key in the datastore on production, but during testing it doesn't really matter. 

As for your questions:

1. We have imagefields working in tests, I'm not sure what's going on here, I haven't seen that error before. Which SDK version are you using?
2. I haven't seen the migrate error before (we do have projects using Nose and the nose plugin) do you have a stack trace of that error?
3. Answered above
4. The problem seems to be that the URL that urlfetch is using is coming from the testbed (when it should be localhost... not testbed.example.com) I've never seen this before

**Comment by farridav** [comment]
Yes I have updated my manage.py (as per the docs) to use the test sandbox when 'test' is in sys.argv, so I'm definitely using that, that said, I have now managed to step around the secret key issue by returning some defaults when the datastore is not available

Your suggestion is a valid approach (only pulling secrets from the datastore in a production like environment), though I'm generally in favour of minimising the differences between development and production, especially when the differences contain moving parts.

After having done some more research, I think maybe the urlfetch issue is something to do with the AppEngine SDK, as I have tried rolling Djangae back to earlier versions again, and see that error is still occurring.. (most likely there is a bug caused by me rolling back the cloud SDK)

I'm hoping it goes away once https://github.com/potatolondon/djangae/issues/873 is fit for merge, then I can use the latest SDK, and Djangae build...In the meantime I am using djangos FileSystemStorage in tests, and have pinned my cloud SDK version.

As for the migrate error, it appears to come from Django-nose [here](https://github.com/django-nose/django-nose/blob/master/django_nose/plugin.py#L64), it tries to set the databases up early on, here's my stacktrace having removed the `begin` call in your nose plugin https://pastebin.com/hizPNXGp

And here is a brief summary of my test setup:

```
DATABASES = {
    'sql': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, '.storage', 'db.sqlite3'),
        'TEST': {
            'NAME': ':memory:',
        },
    },
    'nosql': {
        'ENGINE': 'djangae.db.backends.appengine'
    }
}

INSTALLED_APPS = list(INSTALLED_APPS) + [
    'django_nose',
]

TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'
NOSE_PLUGINS = ['djangae.noseplugin.DjangaePlugin']
```

I'm using AppEngine SDK 1.9.50, inside of the gcloud SDK version 147.0.0, thanks for your feedback on this

UPDATE: I _think_ the reason the setup (and teardown) db is being called for me and not you, is because i have an in `:memory:` db defined, if you add 

```
        'TEST': {
            'NAME': ':memory:',
        },
```

to your db dict, you may find your able to repro the error...

**Comment by farridav** [comment]
I can confirm this resolves my problem, and I'm able to stop using my own fork..

Thanks for the speedy response
