### ISSUE TITLE
Deserialized SetField cannot be loaded back with loadData 

### ISSUE THREAD

**Issue by dannymilsom** [potatolondon/djangae#881]
If you have a model with a `SetField`, export the model with `dumpdata` in JSON format, and then try to insert back into the datastore with `loaddata`, a `DeserializationError` is raised which halts the process.

```
django.core.serializers.base.DeserializationError: Problem installing fixture 'data.json': Unable to parse string into iterable field: field_value was '[u'es']'
```

From quickly looking at the code it looks like we deserialized the `SetField` into a a string containing a list...

```
def value_to_string(self, obj):
    """
    Custom method for serialization, as JSON doesn't support serializing sets.
    """
    return str(list(self._get_val_from_obj(obj)))
```

But when we load the data, the `to_python` special casing to transform the string into a set or list fails, as the field type is a set but the string does not start with `{`, so no transformation occurs.

```
if (self._iterable_type == set and value.startswith("{") and value.endswith("}")) or \
    (self._iterable_type == list and value.startswith("[") and value.endswith("]")):
        value = [x.strip() for x in value[1:-1].split(",") ]
```

**Comment by nealedj** [comment]
Previously referenced here (but fixed elsewhere) https://github.com/potatolondon/djangae/pull/375
