### ISSUE TITLE
Add instructions of how to contribute to the project

### ISSUE THREAD

**Issue by davide-ceretti** [potatolondon/djangae#89]
E.g.:
* how to install the app in develop mode
* how to run unit tests
* coding standards

Adding a tox.ini that run tests against different supported versions of Python/Django and/or different backends would be great!

**Comment by adamalton** [comment]
I think that everything on here is now covered with the exception of coding standards/guidelines.

**Comment by davide-ceretti** [comment]
:+1: Thanks
