### ISSUE TITLE
#887 is missing from CHANGELOG

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#896]
[This commit](https://github.com/potatolondon/djangae/commit/37c7a9064d7a04a4241af54a8003f121f2190ccf) was tagged to close #887, but it didn't include a CHANGELOG entry for the change.  So #887 was closed (not merged), meaning we've now fixed something which isn't in the CHANGELOG.

**Comment by grzes** [comment]
I added one sentence for the changes from pr: https://github.com/potatolondon/djangae/pull/893.
The bit fixing 887 is mentioned as "... and corrected disable_cache behaviour."
