### ISSUE TITLE
Issue using --sandbox remote

### ISSUE THREAD

**Issue by farridav** [potatolondon/djangae#898]
I'm having trouble using `--sandbox remote`, because when starting the oauth2 flow, djangae imports some constants from `appcfg` https://github.com/potatolondon/djangae/blob/master/djangae/sandbox.py#L240, and within that app engine module, there's an oauth2 import that fails `from oauth2client import devshell` when you have a later version of `oauth2client` installed.

In my case this comes from having `google-cloud-bigquery==0.22.1` installed, when the import fails, it gets caught in djangae, and tries to auth using username/password (Which fails with a 404 `urllib2.HTTPError: HTTP Error 404: Not Found`)

- I think there may be a Djangae bug with username/password authentication
- What's the best way to report this issue to appengine?
- If resolution upstream is slow, Is there any way of mitigating the issue within Djangae?

**Comment by moggers87** [comment]
This might help: https://github.com/potatolondon/djangae/issues/856#issuecomment-285403026

**Comment by farridav** [comment]
Unfortunately I need to use a later `oauth2client` version for something else in my project, so pinning it wont help me.. I have managed to temporarily step around this issue by going back to my fork of Djangae again, commenting out the import [here](https://github.com/potatolondon/djangae/blob/master/djangae/sandbox.py#L240) and replacing it with the hardcoded values it was trying to import (namely `APPCFG_CLIENT_ID` and `APPCFG_CLIENT_NOTSOSECRET`).

Obviously this is not ideal in case those values change, an ideal fix would be for appengine to not `from oauth2client import devshell` in `google.appengine.tools.appcfg` and to try/except ImportError like they do with the oauth2 credentials imports in that file.. to conclude:

- The Djangae fallback username/password authentication mechanic is still broken
- Google could do with wrapping their devshell import in a try/except (Hence me asking the best way to report this upstream)

Thanks for reading :)

**Comment by davidwtbuxton** [comment]
Running into the same bug, using recent Djangae commit b5872bb2a1b0425c320537945ed13fd73bd8b6cd and SDK 1.9.57.

With SDK 1.9.50 and earlier, I am prompted to paste the oauth2 challenge into the terminal. With SDK 1.9.51 and later (including 1.9.57) the oauth2 prompt doesn't happen, and instead I am prompted for my username and password. After entering the correct name and password, the command fails with HTTP Error 404 (same as above).

So work-around for me was to use SDK 1.9.50 for the moment.

Traceback here: https://gist.github.com/davidwtbuxton/18208091555036158e09ab42457d45ac
