### ISSUE TITLE
Using only django.contrib.auth and Datastore.

### ISSUE THREAD

**Issue by briva** [potatolondon/djangae#904]
Hello,

I need to create an API with username/password classic auth.

Possible to avoid Google auth and using classic django auth with Google Datastore  ?

I tried to remove :
'djangae.contrib.gauth.datastore'
'djangae.contrib.gauth.middleware.AuthenticationMiddleware'
'djangae.contrib.gauth_datastore.backends.AppEngineUserAPIBackend',

And set django.contrib.auth.models.User User in AUTH_USER_MODEL.

But not working.

Thx

**Comment by davidwtbuxton** [comment]
Hi,

Have you had any luck following the documentation?

http://djangae.readthedocs.io/en/latest/gauth/#usernamepassword-authentication

For questions about using Djangae, please use the Google group. When posting to the group, please include as much relevant detail as possible, including the versions of Djangae and Django you are using. GitHub issues are best used for reporting bugs in the Djangae code and making feature requests.

https://groups.google.com/forum/#!forum/djangae-users

Hope this helps,

David B.
