### ISSUE TITLE
Linear time on get query set datastore.

### ISSUE THREAD

**Issue by briva** [potatolondon/djangae#910]
I'm currently setup djangae with the cloud Datastore.

I've a simple route which return a list of items.

But the time calls seem increase linearly with the increasing of items.

**Exemple with 300 items in my database:*
FeedPost.objects.order_by("-date_post")[:5].all()
1048.34ms

**Exemple with 600 items in my database :**
FeedPost.objects.order_by("-date_post")[:5].all()
2120.25ms

Maybe there is a problem with limit on query set ?

Thx

**Comment by Kazade** [comment]
Yeah that doesn't seem right... I'll take a look

**Comment by briva** [comment]
Effectively, not the same pb in production.

This is weird.

Btw, when i watch my entities through the admin local server, no long time response. The time response not increase with amount of items.

**Comment by Kazade** [comment]
OK, I'm going to assume this is a problem with the datastore stub and not something wrong with Djangae as such. Feel free to reopen if you disagree :)
