### ISSUE TITLE
Model.objects.filter(pk__gt=0) never returns results

### ISSUE THREAD

**Issue by nealedj** [potatolondon/djangae#913]
Given a standard model with the default primary key I was expecting `Model.objects.filter(pk__gt=0)` to return all objects since the IDs allocated by the datastore are always positive.

This query always returns an empty result set. It seems that `WhereNode.will_never_return_results` gets set if the right hand value is 0. See https://github.com/potatolondon/djangae/blob/master/djangae/db/backends/appengine/query.py#L138. This makes sense for equality queries because 0 is a value that would never be allocated for an object.

The behaviour makes sense now I've looked into it but I think it's quite unintuitive.

`Model.objects.filter(pk__gt=1)` will return results.

If a primary key field is manually declared then it will also return results. I.e.

    class Model(models.Model):
        a_custom_id = models.IntegerField(primary_key=True)

**Comment by adamalton** [comment]
It seems like we could fix this fairly easily with a tiny bit more logic in
there, right?

It does seem wrong that `pk__gte=1 will return results, but `pk__gt=0` will
return nothing.
