### ISSUE TITLE
Release `0.9.10-alpha` to pypi

### ISSUE THREAD

**Issue by farridav** [potatolondon/djangae#931]
I see the setup.py references `0.9.10-alpha` but i cant find that on pypi

> Could not find a version that satisfies the requirement Djangae==0.9.10-alpha (from versions: 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9)

Any chance of a release to pypi?, better still (and in the true spirit of continuous integration) an auto tag and pypi upload on merge to master ?

Thanks in advance, and keep up the good work !

**Comment by Kazade** [comment]
Pushing Alpha releases to Pypi is something that hadn't occurred to me, I'll see if we can sort that out

**Comment by farridav** [comment]
I think that asking for the latest version with `pip install -u Djangae` will ignore alpha releases.. but it'd be worth a test to ensure breaking changes are not introduced to those not expecting them..

**Comment by seawolf42** [comment]
According to [Pre-release Versions](https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions) in the pip install guide:

> Starting with v1.4, pip will only install stable versions as specified by PEP426 by default. If a version cannot be parsed as a compliant PEP426 version then it is assumed to be a pre-release.
>
> If a Requirement specifier includes a pre-release or development version (e.g. >=0.0.dev0) then pip will allow pre-release and development versions for that requirement. This does not include the != flag.
>
> The pip install command also supports a --pre flag that will enable installing pre-releases and development releases.

**Comment by farridav** [comment]
Great, once this issue is closed I'll presume the alpha release is on pypi :)

**Comment by moggers87** [comment]
This can be closed now [0.9.10 has been released](https://github.com/potatolondon/djangae/releases/tag/v0.9.10). Unless we want to discuss alpha releases some more?

**Comment by davidwtbuxton** [comment]
Current PyPI release is 0.9.11 https://pypi.org/project/djangae/0.9.11/
