### ISSUE TITLE
Big files upload error

### ISSUE THREAD

**Issue by dissdoc** [potatolondon/djangae#937]
Hi all!
I have a problem with upload files.
If I upload file (for example) 280kb - it's OK. (request.data has a file)
Bu if I upload file more (or about) 1mb - I get a problem: request.data is None

**Comment by moggers87** [comment]
If you have a general support query, you might find posting to the djangae-users group will get you a quicker response: https://groups.google.com/forum/#!forum/djangae-users

Some more information would also be helpful (e.g. is there anything in logs? Is this on the local dev server or on app engine itself? What's `request.data` from? It's not something found on a normal Django `HttpRequest`)

Thanks!

**Comment by davidwtbuxton** [comment]
Check the value of [Django's FILE_UPLOAD_MAX_MEMORY_SIZE setting][1].

For handling very large uploads, [the SDK supports saving directly to the blobstore or cloud storage][2].

I'm closing this ticket. If you believe you have found a bug in Djangae, please re-open it.

David

[1]: https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-FILE_UPLOAD_MAX_MEMORY_SIZE
[2]: https://cloud.google.com/appengine/docs/standard/python/blobstore/#Python_Uploading_a_blob
