### ISSUE TITLE
Unable to paginate in reverse based on datetime

### ISSUE THREAD

**Issue by meizon** [potatolondon/djangae#947]
In this function, reversing a datetime string representation isn't going to work as expected:

```
if neg:
    # this creates the alphabetical mirror of a string, e.g. ab => zy, but for the full
    # range of unicode characters, e.g. first unicode char => last unicode char, etc
    value = u"".join([ unichr(0xffff - ord(x)) for x in value ])
```

It results in incorrect pagination based on datetimes.

**Comment by Kazade** [comment]
I don't understand why it wouldn't work... datetimes would be converted to isoformat, which is alphabetically orderable, then that code just reverses the order. Are you passing a string which isn't in isoformat?

**Comment by meizon** [comment]
I've added logging in to show that it does call the isoformat check inside the paginator but still doesn't work as expected. We are using `('-modified_on',)` as the orderings but it just always orders like it would without the `-`.

**Comment by adamalton** [comment]
I've played around with this string reversal stuff:

```python
value = u"".join([ unichr(0xffff - ord(x)) for x in value ])
```

using different values of `unicode(datetime.now().isoformat())`.  And it seems to work as it should do.

So my guess is that the bug must be in a different part of the magic...?

**Comment by meizon** [comment]
Yeah, I can take another look to see where the issue lies. Meanwhile, I'm using djangae's core Paginator, but would love to use this better one.
