### ISSUE TITLE
manage.py runserver host:port broken on 0.9.10

### ISSUE THREAD

**Issue by philoozushi** [potatolondon/djangae#948]
With 0.9.10, `runserver` command with custom port (and host) has broken.

E.g. `./manage.py runserver 0.0.0.0:7350`

```
System check identified no issues (0 silenced).
July 24, 2017 - 12:14:45
Django version 1.10, using settings 'settings'
Starting development server at http://0.0.0.0:7350/
Quit the server with CONTROL-C.

INFO     2017-07-24 12:14:45,650 devappserver2.py:116] Skipping SDK update check.
INFO     2017-07-24 12:14:45,652 api_server.py:313] Starting API server at: http://0.0.0.0:8010
INFO     2017-07-24 12:14:45,655 dispatcher.py:226] Starting module "default" running at: http://0.0.0.0:8000
INFO     2017-07-24 12:14:45,661 admin_server.py:116] Starting admin server at: http://0.0.0.0:8011
```

The ports aren't configured properly anymore.

@Kazade I found this commit: 5d20e7c981af6f9b737517f70820bf776e86ab3d where you remove the port configuration in `djangae/management/commands/runserver.py`, is there a reason for that?
If you need to keep the default port values as constants in `djangae/sandbox.py`, maybe we could have the configuration back in `runserver.py`  that would override the constants?

Thanks!

**Comment by philoozushi** [comment]
To be more precise, the 3 following dev_appserver.py options: `port`, `admin_port`, `api_port` don't work anymore.

**Comment by Kazade** [comment]
Hmm, sorry! Getting this working on 1.9.54+ is a pain - removing the ability to override was an accident. I'll take a look when I can.
