### ISSUE TITLE
`BindError` exception with Djangae 0.9.10 and SDK 1.9.57

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#954]
Hi,

I recently updated a project which was using Djangae 0.9.7 (installed from PyPI) so that it would work with the latest App Engine SDK.

Since updating I have been seeing a lot of errors when trying to run the dev server on my local machine with `./manage.py runserver`. The error is:

```
google.appengine.tools.devappserver2.wsgi_server.BindError: Unable to bind 127.0.0.1:8011
```

If I do `./manage.py runserver` then it will start the first time. I then kill the server after a few requests in my browser, and it shuts down within a few seconds as expected.

But if I then start the server again with `./manage.py runserver`, a lot of the time it will fail to start with the `BindError` exception. When this fails, before the exception is raised, the console shows messages that I usually see when the dev server is shutting down. Specifically, there are messages about "Saving search indexes".

It's as if the startup process is trying to shutdown the App Engine admin server, even though the server appeared to shut down cleanly on the previous run. The bind error kind of makes sense, in that it seems like there's a phantom admin server process still running from the previous session.

If I wait a few minutes before trying to start the dev server again, it tends to work. Not sure what the exact definition of "a few minutes" is.

My guess is that the admin server isn't being shut down cleanly, and it is hanging around even after the runserver process has exited, and it is still bound to the admin server port. And then when starting the dev server again, Djangae fails to start the admin server (because the zombie admin server is still listening on the same port) and I get a few minutes to write up bug reports in GitHub.

I'm getting a bit screwy trying to isolate a log of what is happening with removing sensitive details and stuff. I'll update this ticket shortly.

David

**Comment by Kazade** [comment]
So this seemed to start happening with the 1.9.54 SDK, it doesn't happen with 1.9.51 so something changed somewhere between those two.

It appears that it takes a while for the server to really exit. If you wait a while then try again it works. I have no idea what's going on :/

**Comment by davidwtbuxton** [comment]
Closing, I _think_ this got solved somehow.
