### ISSUE TITLE
Improve 'dumpurls' for class-based views

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#963]
It should:

 - List parent classes
 - List decorators applied to dispatch, get, post etc.
 - List the allowed methods (this column can be for both FBVs and CBVs, but it's obvious by the decorators on FBVs anyway)

**Comment by adamalton** [comment]
Are you thinking that it should list all parent classes (all the way up the tree)?  If so, that could be a lot of output for some views!
