### ISSUE TITLE
manage.py help text is not shown

### ISSUE THREAD

**Issue by igniteflow** [potatolondon/djangae#981]
Would you like assistance or advice?  Please using the [djangae mailing list](https://groups.google.com/forum/#!forum/djangae-users) ([djangae-users@googlegroups.com](mailto:djangae-users@googlegroups.com)) for questions and discussion.

Issue description

manage.py help text is not shown (see steps to reproduce)

Steps to reproduce

Install Django and Djangae separately and run any mangement command passing the `--help` flag.  Notice that regardless of the command used, Djangae will always output

```
usage: manage.py [-h] [--sandbox {test,remote,local}] [--app_id APP_ID]

optional arguments:
  -h, --help            show this help message and exit
  --sandbox {test,remote,local}
  --app_id APP_ID       GAE APPLICATION ID
```
Swallowing the help text of the management command

Traceback or other info

* Djangae version: 0.9.10 / master@07b8062fae760f3a125be891571c5cdfc61fb0e1
* Django version: 1.8.19
* App Engine SDK version: 1.9.54
* Using Cloud SDK: no

**Comment by seawolf42** [comment]
@igniteflow are you taking this one? If not, I'd be happy to work it.

**Comment by igniteflow** [comment]
@seawolf42 thanks for the offer, however I've already started on this
