### ISSUE TITLE
Change default value of failure_behaviour in process_task_queues

### ISSUE THREAD

**Issue by nealedj** [potatolondon/djangae#989]
The default behaviour when calling `process_task_queues()` in a unit test is for the logic run within those tasks to fail silently - `TaskFailedBehaviour.DO_NOTHING`.

I find that this leads to tests failing because of the side effects of these failed tasks and it often isn't immediately obvious that a failure within the task processing is the root cause. The INFO level log is easy to miss.

I'd suggest that the default value for `failure_behaviour` should be `TaskFailedBehaviour.RAISE_ERROR)`

**Comment by Kazade** [comment]
Agreed
